dist: bionic
language: nim
compiler:
    - nim
addons:
    apt:
        packages:
            - python3
            - python3-pip
            - python3-setuptools

before_install:
    - pip3 install -U setuptools
    - pip3 install online-judge-tools
    - sudo apt install nim
script:
    - nim --version
    - ./test.sh
