/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/chaemon/.choosenim/toolchains/nim-0.13.0/lib -o /home/chaemon/git/library-1/nim/math/nimcache/divisor.o /home/chaemon/git/library-1/nim/math/nimcache/divisor.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
typedef struct TY93014 TY93014;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef struct {
N_NIMCALL_PTR(NI, ClPrc) (NI x_93102, NI y_93104, void* ClEnv);
void* ClEnv;
} TY93100;
typedef N_CLOSURE_PTR(NI, TMP170) (NI x_93089, NI y_93091, void* ClEnv);
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY93014 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_NIMCALL(TY93014*, newseq_93009)(NI len);
N_NIMCALL(NI, cmp_93079)(NI x, NI y);
N_NIMCALL(void, sort_93093)(NI* a, NI aLen0, TY93100 cmp, NU8 order);
N_NIMCALL(void, merge_93138)(NI* a, NI aLen0, NI* b, NI bLen0, NI lo, NI m, NI hi, TY93100 cmp, NU8 order);
N_NIMCALL(TY93014*, divisor_93001)(NI n);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, HEX24_94438)(TY93014* x);
N_NIMCALL(NimStringDesc*, collectiontostring_94446)(TY93014* x, NimStringDesc* b, NimStringDesc* e);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, divisorInit000)(void);
NIM_EXTERNC N_NOINLINE(void, divisorDatInit000)(void);
extern TFrame* frameptr_19436;

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	result = (NI)(a % b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(TY93014*, divisor_93001)(NI n) {
	TY93014* result;
	NI i;
	TY93100 LOC11;
	nimfr("divisor", "divisor.nim")
	result = 0;
	nimln(4, "divisor.nim");
	result = newseq_93009(((NI) 0));
	nimln(5, "divisor.nim");
	i = ((NI) 1);
	{
		nimln(6, "divisor.nim");
		while (1) {
			NI TMP165;
			NI TMP169;
			TMP165 = mulInt(i, i);
			if (!((NI)(TMP165) <= n)) goto LA2;
			nimln(7, "divisor.nim");
			{
				NI TMP166;
				TMP166 = modInt(n, i);
				if (!((NI)(TMP166) == ((NI) 0))) goto LA5;
				nimln(8, "divisor.nim");
				result = (TY93014*) incrSeqV2(&(result)->Sup, sizeof(NI));
				result->data[result->Sup.len] = i;
				++result->Sup.len;
				nimln(9, "divisor.nim");
				{
					NI TMP167;
					NI TMP168;
					nimln(349, "system.nim");
					nimln(9, "divisor.nim");
					TMP167 = mulInt(i, i);
					if (!!(((NI)(TMP167) == n))) goto LA9;
					TMP168 = divInt(n, i);
					result = (TY93014*) incrSeqV2(&(result)->Sup, sizeof(NI));
					result->data[result->Sup.len] = (NI)(TMP168);
					++result->Sup.len;
				}
				LA9: ;
			}
			LA5: ;
			nimln(10, "divisor.nim");
			TMP169 = addInt(i, ((NI) 1));
			i = (NI)(TMP169);
		} LA2: ;
	}
	nimln(11, "divisor.nim");
	memset((void*)(&LOC11), 0, sizeof(LOC11));
	LOC11.ClPrc = ((TMP170) (cmp_93079)); LOC11.ClEnv = NIM_NIL;
	sort_93093(result->data, result->Sup.len, LOC11, ((NU8) 1));
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_algorithmDatInit000();
	divisorDatInit000();
	stdlib_algorithmInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	divisorInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, divisorInit000)(void) {
	TY93014* LOC1;
	NimStringDesc* LOC2;
	nimfr("divisor", "divisor.nim")
	nimln(13, "divisor.nim");
	LOC1 = 0;
	LOC1 = divisor_93001(((NI) 120));
	LOC2 = 0;
	LOC2 = HEX24_94438(LOC1);
	printf("%s\012", LOC2? (LOC2)->data:"nil");
	fflush(stdout);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, divisorDatInit000)(void) {
}

