/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/chaemon/.choosenim/toolchains/nim-0.13.0/lib -o /home/chaemon/git/library-1/nim/standard_library/nimcache/complex.o /home/chaemon/git/library-1/nim/standard_library/nimcache/complex.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
typedef struct Complex112002 Complex112002;
typedef struct TY112405 TY112405;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  Complex112002  {
NF re;
NF im;
};
struct TY112405 {
NF Field0;
NF Field1;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(Complex112002, complex_112005)(NF re, NF im);
N_NIMCALL(NF, abs_112021)(Complex112002 z);
N_NIMCALL(NF, abs2_112025)(Complex112002 z);
N_NIMCALL(Complex112002, conjugate_112029)(Complex112002 z);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_112033)(Complex112002 x, Complex112002 y);
N_NIMCALL(Complex112002, HEX2B_112038)(NF x, Complex112002 y);
N_NIMCALL(Complex112002, HEX2B_112043)(Complex112002 x, NF y);
N_NIMCALL(Complex112002, HEX2B_112048)(Complex112002 x, Complex112002 y);
N_NIMCALL(Complex112002, HEX2D_112053)(Complex112002 z);
N_NIMCALL(Complex112002, HEX2D_112057)(NF x, Complex112002 y);
N_NIMCALL(Complex112002, HEX2D_112062)(Complex112002 x, NF y);
N_NIMCALL(Complex112002, HEX2D_112067)(Complex112002 x, Complex112002 y);
N_NIMCALL(Complex112002, HEX2A_112072)(Complex112002 x, Complex112002 y);
N_NIMCALL(Complex112002, HEX2A_112077)(NF x, Complex112002 y);
N_NIMCALL(Complex112002, HEX2A_112082)(Complex112002 x, NF y);
N_NIMCALL(Complex112002, HEX2F_112087)(Complex112002 x, NF y);
N_NIMCALL(Complex112002, inv_112092)(Complex112002 z);
N_NIMCALL(Complex112002, HEX2F_112096)(NF x, Complex112002 y);
N_NIMCALL(Complex112002, HEX2F_112101)(Complex112002 x, Complex112002 y);
N_NIMCALL(void, HEX2BHEX3D_112110)(Complex112002* x, Complex112002 y);
static N_INLINE(void, HEX2BHEX3D_104803)(NF* x, NF y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, HEX2DHEX3D_112135)(Complex112002* x, Complex112002 y);
static N_INLINE(void, HEX2DHEX3D_104756)(NF* x, NF y);
N_NIMCALL(void, HEX2AHEX3D_112160)(Complex112002* x, Complex112002 y);
N_NIMCALL(void, HEX2FHEX3D_112166)(Complex112002* x, Complex112002 y);
N_NIMCALL(Complex112002, sqrt_112171)(Complex112002 z);
N_NIMCALL(Complex112002, exp_112183)(Complex112002 z);
N_NIMCALL(Complex112002, ln_112189)(Complex112002 z);
N_NIMCALL(Complex112002, log10_112193)(Complex112002 z);
N_NIMCALL(Complex112002, log2_112197)(Complex112002 z);
N_NIMCALL(Complex112002, pow_112201)(Complex112002 x, Complex112002 y);
N_NIMCALL(Complex112002, pow_112212)(Complex112002 x, NF y);
N_NIMCALL(Complex112002, sin_112217)(Complex112002 z);
N_NIMCALL(Complex112002, arcsin_112221)(Complex112002 z);
N_NIMCALL(Complex112002, cos_112234)(Complex112002 z);
N_NIMCALL(Complex112002, arccos_112238)(Complex112002 z);
N_NIMCALL(Complex112002, tan_112247)(Complex112002 z);
N_NIMCALL(Complex112002, arctan_112251)(Complex112002 z);
N_NIMCALL(Complex112002, cot_112270)(Complex112002 z);
N_NIMCALL(Complex112002, arccot_112274)(Complex112002 z);
N_NIMCALL(Complex112002, sec_112293)(Complex112002 z);
N_NIMCALL(Complex112002, arcsec_112298)(Complex112002 z);
N_NIMCALL(Complex112002, csc_112311)(Complex112002 z);
N_NIMCALL(Complex112002, arccsc_112316)(Complex112002 z);
N_NIMCALL(Complex112002, sinh_112330)(Complex112002 z);
N_NIMCALL(Complex112002, arcsinh_112335)(Complex112002 z);
N_NIMCALL(Complex112002, cosh_112339)(Complex112002 z);
N_NIMCALL(Complex112002, arccosh_112344)(Complex112002 z);
N_NIMCALL(Complex112002, tanh_112349)(Complex112002 z);
N_NIMCALL(Complex112002, arctanh_112353)(Complex112002 z);
N_NIMCALL(Complex112002, sech_112360)(Complex112002 z);
N_NIMCALL(Complex112002, arcsech_112365)(Complex112002 z);
N_NIMCALL(Complex112002, csch_112373)(Complex112002 z);
N_NIMCALL(Complex112002, arccsch_112378)(Complex112002 z);
N_NIMCALL(Complex112002, coth_112385)(Complex112002 z);
N_NIMCALL(Complex112002, arccoth_112389)(Complex112002 z);
N_NIMCALL(NF, phase_112398)(Complex112002 z);
N_NIMCALL(TY112405, polar_112402)(Complex112002 z);
N_NIMCALL(Complex112002, rect_112412)(NF r, NF phi);
N_NIMCALL(NimStringDesc*, HEX24_112417)(Complex112002 z);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NIM_BOOL, HEX3DHEX7E_112421)(Complex112002 x, Complex112002 y);
N_NIMCALL(NIM_BOOL, HEX3DHEX7E_112426)(Complex112002 x, NF y);
N_NOINLINE(void, raiseassert_89093)(NimStringDesc* msg);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, complexInit000)(void);
NIM_EXTERNC N_NOINLINE(void, complexDatInit000)(void);
STRING_LITERAL(TMP263, "(", 1);
STRING_LITERAL(TMP264, ", ", 2);
STRING_LITERAL(TMP265, ")", 1);
STRING_LITERAL(TMP266, "a / 2.0\'f64 =~ complex(0.5\'f64, 1.0\'f64) ", 41);
STRING_LITERAL(TMP267, "a == a ", 7);
STRING_LITERAL(TMP268, "a - a == z ", 11);
STRING_LITERAL(TMP269, "a + b == z ", 11);
STRING_LITERAL(TMP270, "a + b =~ 0.0\'f64 ", 17);
STRING_LITERAL(TMP271, "a / b == m1 ", 12);
STRING_LITERAL(TMP272, "1.0\'f64 / a =~ complex(0.2\'f64, -0.4) ", 38);
STRING_LITERAL(TMP273, "a * b == complex(3.0\'f64, -4.0) ", 32);
STRING_LITERAL(TMP274, "10.0\'f64 * a == tt ", 19);
STRING_LITERAL(TMP275, "a * 10.0\'f64 == tt ", 19);
STRING_LITERAL(TMP276, "tt / 10.0\'f64 == a ", 19);
STRING_LITERAL(TMP277, "oo + -1.0 == i ", 15);
STRING_LITERAL(TMP278, "-1.0 + oo == i ", 15);
STRING_LITERAL(TMP279, "abs(oo) == sqrt(2.0\'f64) ", 25);
STRING_LITERAL(TMP280, "conjugate(a) == complex(1.0\'f64, -2.0) ", 39);
STRING_LITERAL(TMP281, "sqrt(m1) == i ", 14);
STRING_LITERAL(TMP282, "exp(ipi) =~ m1 ", 15);
STRING_LITERAL(TMP283, "pow(a, b) =~ complex(-3.72999124927876, -1.68815826725068) ", 59);
STRING_LITERAL(TMP284, "pow(z, a) =~ complex(0.0\'f64, 0.0\'f64) ", 39);
STRING_LITERAL(TMP285, "pow(z, z) =~ complex(1.0\'f64, 0.0\'f64) ", 39);
STRING_LITERAL(TMP286, "pow(a, one) =~ a ", 17);
STRING_LITERAL(TMP287, "pow(a, m1) =~ complex(0.2\'f64, -0.4) ", 37);
STRING_LITERAL(TMP288, "pow(a, 2.0\'f64) =~ complex(-3.0, 4.0\'f64) ", 42);
STRING_LITERAL(TMP289, "pow(a, 2) =~ complex(-3.0, 4.0\'f64) ", 36);
STRING_LITERAL(TMP290, "not (pow(a, 2.0\'f64) =~ a) ", 27);
STRING_LITERAL(TMP291, "ln(a) =~ complex(0.80471895621705\'f64, 1.10714871779409\'f64) ", 61);
STRING_LITERAL(TMP292, "log10(a) =~ complex(0.349485002168009\'f64, 0.480828578784234\'f6"
"4) ", 66);
STRING_LITERAL(TMP293, "log2(a) =~ complex(1.16096404744368\'f64, 1.59727796468811\'f64) ", 63);
STRING_LITERAL(TMP294, "sin(a) =~ complex(3.16577851321617\'f64, 1.95960104142161\'f64) ", 62);
STRING_LITERAL(TMP295, "cos(a) =~ complex(2.03272300701967\'f64, -3.0518977991518) ", 58);
STRING_LITERAL(TMP296, "tan(a) =~ complex(0.0338128260798967\'f64, 1.014793616146634\'f64"
") ", 65);
STRING_LITERAL(TMP297, "cot(a) =~ 1.0\'f64 / tan(a) ", 27);
STRING_LITERAL(TMP298, "sec(a) =~ 1.0\'f64 / cos(a) ", 27);
STRING_LITERAL(TMP299, "csc(a) =~ 1.0\'f64 / sin(a) ", 27);
STRING_LITERAL(TMP300, "arcsin(a) =~ complex(0.427078586392476\'f64, 1.528570919480998\'f"
"64) ", 67);
STRING_LITERAL(TMP301, "arccos(a) =~ complex(1.14371774040242\'f64, -1.528570919481) ", 60);
STRING_LITERAL(TMP302, "arctan(a) =~ complex(1.338972522294494\'f64, 0.402359478108525\'f"
"64) ", 67);
STRING_LITERAL(TMP303, "arccot(a) =~ complex(0.2318238045004031\'f64, -0.402359478108525"
") ", 65);
STRING_LITERAL(TMP304, "arcsec(a) =~ complex(1.384478272687081\'f64, 0.3965682301123288\'"
"f64) ", 68);
STRING_LITERAL(TMP305, "arccsc(a) =~ complex(0.1863180541078155\'f64, -0.396568230112329"
"1) ", 66);
STRING_LITERAL(TMP306, "cosh(a) =~ complex(-0.64214812471552, 1.068607421382778\'f64) ", 61);
STRING_LITERAL(TMP307, "sinh(a) =~ complex(-0.489056259041294, 1.40311925062204\'f64) ", 61);
STRING_LITERAL(TMP308, "tanh(a) =~ complex(1.16673625724092\'f64, -0.243458201185725) ", 61);
STRING_LITERAL(TMP309, "sech(a) =~ 1.0\'f64 / cosh(a) ", 29);
STRING_LITERAL(TMP310, "csch(a) =~ 1.0\'f64 / sinh(a) ", 29);
STRING_LITERAL(TMP311, "coth(a) =~ 1.0\'f64 / tanh(a) ", 29);
STRING_LITERAL(TMP312, "arccosh(a) =~ complex(1.528570919480998\'f64, 1.14371774040242\'f"
"64) ", 67);
STRING_LITERAL(TMP313, "arcsinh(a) =~ complex(1.469351744368185\'f64, 1.06344002357775\'f"
"64) ", 67);
STRING_LITERAL(TMP314, "arctanh(a) =~ complex(0.173286795139986\'f64, 1.17809724509617\'f"
"64) ", 67);
STRING_LITERAL(TMP315, "arcsech(a) =~ arccosh(1.0\'f64 / a) ", 35);
STRING_LITERAL(TMP316, "arccsch(a) =~ arcsinh(1.0\'f64 / a) ", 35);
STRING_LITERAL(TMP317, "arccoth(a) =~ arctanh(1.0\'f64 / a) ", 35);
STRING_LITERAL(TMP318, "phase(a) == 1.10714871779409\'f64 ", 33);
STRING_LITERAL(TMP319, "rect(t.r, t.phi) =~ a ", 22);
STRING_LITERAL(TMP320, "rect(1.0\'f64, 2.0\'f64) =~ complex(-0.4161468365471424, 0.909297"
"4268256817\'f64) ", 79);
STRING_LITERAL(TMP321, "sizeof(a) == 16 ", 16);
STRING_LITERAL(TMP322, "complex(0, 123.0\'f64) + 456.0\'f64 == complex(456, 123) ", 55);
extern TFrame* frameptr_19436;
Complex112002 z_112431;
Complex112002 oo_112432;
Complex112002 a_112433;
Complex112002 b_112436;
Complex112002 m1_112438;
Complex112002 i_112439;
Complex112002 one_112440;
Complex112002 tt_112441;
Complex112002 ipi_112443;
TY112405 t_112461;

N_NIMCALL(Complex112002, complex_112005)(NF re, NF im) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	result.re = re;
	result.im = im;
	return result;
}

N_NIMCALL(NF, abs_112021)(Complex112002 z) {
	NF result;
	result = 0;
	result = hypot(z.re, z.im);
	return result;
}

N_NIMCALL(NF, abs2_112025)(Complex112002 z) {
	NF result;
	result = 0;
	result = ((NF)(((NF)(z.re) * (NF)(z.re))) + (NF)(((NF)(z.im) * (NF)(z.im))));
	return result;
}

N_NIMCALL(Complex112002, conjugate_112029)(Complex112002 z) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	result.re = z.re;
	result.im = -(z.im);
	return result;
}

N_NIMCALL(NIM_BOOL, HEX3DHEX3D_112033)(Complex112002 x, Complex112002 y) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = (x.re == y.re);
	if (!(LOC1)) goto LA2;
	LOC1 = (x.im == y.im);
	LA2: ;
	result = LOC1;
	return result;
}

N_NIMCALL(Complex112002, HEX2B_112038)(NF x, Complex112002 y) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	result.re = ((NF)(x) + (NF)(y.re));
	result.im = y.im;
	return result;
}

N_NIMCALL(Complex112002, HEX2B_112043)(Complex112002 x, NF y) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	result.re = ((NF)(x.re) + (NF)(y));
	result.im = x.im;
	return result;
}

N_NIMCALL(Complex112002, HEX2B_112048)(Complex112002 x, Complex112002 y) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	result.re = ((NF)(x.re) + (NF)(y.re));
	result.im = ((NF)(x.im) + (NF)(y.im));
	return result;
}

N_NIMCALL(Complex112002, HEX2D_112053)(Complex112002 z) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	result.re = -(z.re);
	result.im = -(z.im);
	return result;
}

N_NIMCALL(Complex112002, HEX2D_112057)(NF x, Complex112002 y) {
	Complex112002 result;
	Complex112002 LOC1;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = HEX2D_112053(y);
	result = HEX2B_112038(x, LOC1);
	return result;
}

N_NIMCALL(Complex112002, HEX2D_112062)(Complex112002 x, NF y) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	result.re = ((NF)(x.re) - (NF)(y));
	result.im = x.im;
	return result;
}

N_NIMCALL(Complex112002, HEX2D_112067)(Complex112002 x, Complex112002 y) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	result.re = ((NF)(x.re) - (NF)(y.re));
	result.im = ((NF)(x.im) - (NF)(y.im));
	return result;
}

N_NIMCALL(Complex112002, HEX2A_112072)(Complex112002 x, Complex112002 y) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	result.re = ((NF)(((NF)(x.re) * (NF)(y.re))) - (NF)(((NF)(x.im) * (NF)(y.im))));
	result.im = ((NF)(((NF)(x.im) * (NF)(y.re))) + (NF)(((NF)(x.re) * (NF)(y.im))));
	return result;
}

N_NIMCALL(Complex112002, HEX2A_112077)(NF x, Complex112002 y) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	result.re = ((NF)(x) * (NF)(y.re));
	result.im = ((NF)(x) * (NF)(y.im));
	return result;
}

N_NIMCALL(Complex112002, HEX2A_112082)(Complex112002 x, NF y) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	result.re = ((NF)(x.re) * (NF)(y));
	result.im = ((NF)(x.im) * (NF)(y));
	return result;
}

N_NIMCALL(Complex112002, HEX2F_112087)(Complex112002 x, NF y) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	result.re = ((NF)(x.re) / (NF)(y));
	result.im = ((NF)(x.im) / (NF)(y));
	return result;
}

N_NIMCALL(Complex112002, inv_112092)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	NF LOC2;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = conjugate_112029(z);
	LOC2 = 0;
	LOC2 = abs2_112025(z);
	result = HEX2F_112087(LOC1, LOC2);
	return result;
}

N_NIMCALL(Complex112002, HEX2F_112096)(NF x, Complex112002 y) {
	Complex112002 result;
	Complex112002 LOC1;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = inv_112092(y);
	result = HEX2A_112077(x, LOC1);
	return result;
}

N_NIMCALL(Complex112002, HEX2F_112101)(Complex112002 x, Complex112002 y) {
	Complex112002 result;
	NF r;
	NF den;
	memset((void*)(&result), 0, sizeof(result));
	r = 0;
	den = 0;
	{
		if (!((y.re > 0? (y.re) : -(y.re)) < (y.im > 0? (y.im) : -(y.im)))) goto LA3;
		r = ((NF)(y.re) / (NF)(y.im));
		den = ((NF)(y.im) + (NF)(((NF)(r) * (NF)(y.re))));
		result.re = ((NF)(((NF)(((NF)(x.re) * (NF)(r))) + (NF)(x.im))) / (NF)(den));
		result.im = ((NF)(((NF)(((NF)(x.im) * (NF)(r))) - (NF)(x.re))) / (NF)(den));
	}
	goto LA1;
	LA3: ;
	{
		r = ((NF)(y.im) / (NF)(y.re));
		den = ((NF)(y.re) + (NF)(((NF)(r) * (NF)(y.im))));
		result.re = ((NF)(((NF)(x.re) + (NF)(((NF)(r) * (NF)(x.im))))) / (NF)(den));
		result.im = ((NF)(((NF)(x.im) - (NF)(((NF)(r) * (NF)(x.re))))) / (NF)(den));
	}
	LA1: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(void, HEX2BHEX3D_104803)(NF* x, NF y) {
	nimfr("+=", "system.nim")
	nimln(3266, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

N_NIMCALL(void, HEX2BHEX3D_112110)(Complex112002* x, Complex112002 y) {
	HEX2BHEX3D_104803((&(*x).re), y.re);
	HEX2BHEX3D_104803((&(*x).im), y.im);
}

static N_INLINE(void, HEX2DHEX3D_104756)(NF* x, NF y) {
	nimfr("-=", "system.nim")
	nimln(3271, "system.nim");
	(*x) = ((NF)((*x)) - (NF)(y));
	popFrame();
}

N_NIMCALL(void, HEX2DHEX3D_112135)(Complex112002* x, Complex112002 y) {
	HEX2DHEX3D_104756((&(*x).re), y.re);
	HEX2DHEX3D_104756((&(*x).im), y.im);
}

N_NIMCALL(void, HEX2AHEX3D_112160)(Complex112002* x, Complex112002 y) {
	NF im;
	im = ((NF)(((NF)((*x).im) * (NF)(y.re))) + (NF)(((NF)((*x).re) * (NF)(y.im))));
	(*x).re = ((NF)(((NF)((*x).re) * (NF)(y.re))) - (NF)(((NF)((*x).im) * (NF)(y.im))));
	(*x).im = im;
}

N_NIMCALL(void, HEX2FHEX3D_112166)(Complex112002* x, Complex112002 y) {
	(*x) = HEX2F_112101((*x), y);
}

N_NIMCALL(Complex112002, sqrt_112171)(Complex112002 z) {
	Complex112002 result;
	NF x;
	NF y;
	NF w;
	NF r;
	memset((void*)(&result), 0, sizeof(result));
	x = 0;
	y = 0;
	w = 0;
	r = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (z.re == 0.0);
		if (!(LOC3)) goto LA4;
		LOC3 = (z.im == 0.0);
		LA4: ;
		if (!LOC3) goto LA5;
		result = z;
	}
	goto LA1;
	LA5: ;
	{
		x = (z.re > 0? (z.re) : -(z.re));
		y = (z.im > 0? (z.im) : -(z.im));
		{
			NF LOC12;
			NF LOC13;
			NF LOC14;
			if (!(y <= x)) goto LA10;
			r = ((NF)(y) / (NF)(x));
			LOC12 = 0;
			LOC12 = sqrt(x);
			LOC13 = 0;
			LOC13 = sqrt(((NF)(1.0000000000000000e+00) + (NF)(((NF)(r) * (NF)(r)))));
			LOC14 = 0;
			LOC14 = sqrt(((NF)(5.0000000000000000e-01) * (NF)(((NF)(1.0000000000000000e+00) + (NF)(LOC13)))));
			w = ((NF)(LOC12) * (NF)(LOC14));
		}
		goto LA8;
		LA10: ;
		{
			NF LOC16;
			NF LOC17;
			NF LOC18;
			r = ((NF)(x) / (NF)(y));
			LOC16 = 0;
			LOC16 = sqrt(y);
			LOC17 = 0;
			LOC17 = sqrt(((NF)(1.0000000000000000e+00) + (NF)(((NF)(r) * (NF)(r)))));
			LOC18 = 0;
			LOC18 = sqrt(((NF)(5.0000000000000000e-01) * (NF)(((NF)(r) + (NF)(LOC17)))));
			w = ((NF)(LOC16) * (NF)(LOC18));
		}
		LA8: ;
		{
			if (!(0.0 <= z.re)) goto LA21;
			result.re = w;
			result.im = ((NF)(z.im) / (NF)(((NF)(w) * (NF)(2.0000000000000000e+00))));
		}
		goto LA19;
		LA21: ;
		{
			{
				if (!(0.0 <= z.im)) goto LA26;
				result.im = w;
			}
			goto LA24;
			LA26: ;
			{
				result.im = -(w);
			}
			LA24: ;
			result.re = ((NF)(z.im) / (NF)(((NF)(result.im) + (NF)(result.im))));
		}
		LA19: ;
	}
	LA1: ;
	return result;
}

N_NIMCALL(Complex112002, exp_112183)(Complex112002 z) {
	Complex112002 result;
	NF rho;
	NF theta;
	NF LOC1;
	NF LOC2;
	memset((void*)(&result), 0, sizeof(result));
	rho = exp(z.re);
	theta = z.im;
	LOC1 = 0;
	LOC1 = cos(theta);
	result.re = ((NF)(rho) * (NF)(LOC1));
	LOC2 = 0;
	LOC2 = sin(theta);
	result.im = ((NF)(rho) * (NF)(LOC2));
	return result;
}

N_NIMCALL(Complex112002, ln_112189)(Complex112002 z) {
	Complex112002 result;
	NF LOC1;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = 0;
	LOC1 = abs_112021(z);
	result.re = log(LOC1);
	result.im = atan2(z.im, z.re);
	return result;
}

N_NIMCALL(Complex112002, log10_112193)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	NF LOC2;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = ln_112189(z);
	LOC2 = 0;
	LOC2 = log(1.0000000000000000e+01);
	result = HEX2F_112087(LOC1, LOC2);
	return result;
}

N_NIMCALL(Complex112002, log2_112197)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	NF LOC2;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = ln_112189(z);
	LOC2 = 0;
	LOC2 = log(2.0000000000000000e+00);
	result = HEX2F_112087(LOC1, LOC2);
	return result;
}

N_NIMCALL(Complex112002, pow_112201)(Complex112002 x, Complex112002 y) {
	Complex112002 result;
	memset((void*)(&result), 0, sizeof(result));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (x.re == 0.0);
		if (!(LOC3)) goto LA4;
		LOC3 = (x.im == 0.0);
		LA4: ;
		if (!LOC3) goto LA5;
		{
			NIM_BOOL LOC9;
			LOC9 = 0;
			LOC9 = (y.re == 0.0);
			if (!(LOC9)) goto LA10;
			LOC9 = (y.im == 0.0);
			LA10: ;
			if (!LOC9) goto LA11;
			result.re = 1.0000000000000000e+00;
			result.im = 0.0;
		}
		goto LA7;
		LA11: ;
		{
			result.re = 0.0;
			result.im = 0.0;
		}
		LA7: ;
	}
	goto LA1;
	LA5: ;
	{
		NIM_BOOL LOC15;
		LOC15 = 0;
		LOC15 = (y.re == 1.0000000000000000e+00);
		if (!(LOC15)) goto LA16;
		LOC15 = (y.im == 0.0);
		LA16: ;
		if (!LOC15) goto LA17;
		result = x;
	}
	goto LA1;
	LA17: ;
	{
		NIM_BOOL LOC20;
		LOC20 = 0;
		LOC20 = (y.re == -1.0000000000000000e+00);
		if (!(LOC20)) goto LA21;
		LOC20 = (y.im == 0.0);
		LA21: ;
		if (!LOC20) goto LA22;
		result = HEX2F_112096(1.0000000000000000e+00, x);
	}
	goto LA1;
	LA22: ;
	{
		NF rho;
		NF theta;
		NF s;
		NF LOC25;
		NF LOC26;
		NF r;
		NF LOC27;
		NF LOC28;
		NF LOC29;
		rho = abs_112021(x);
		theta = atan2(x.im, x.re);
		LOC25 = 0;
		LOC25 = pow(rho, y.re);
		LOC26 = 0;
		LOC26 = exp(((NF)(-(y.im)) * (NF)(theta)));
		s = ((NF)(LOC25) * (NF)(LOC26));
		LOC27 = 0;
		LOC27 = log(rho);
		r = ((NF)(((NF)(y.re) * (NF)(theta))) + (NF)(((NF)(y.im) * (NF)(LOC27))));
		LOC28 = 0;
		LOC28 = cos(r);
		result.re = ((NF)(s) * (NF)(LOC28));
		LOC29 = 0;
		LOC29 = sin(r);
		result.im = ((NF)(s) * (NF)(LOC29));
	}
	LA1: ;
	return result;
}

N_NIMCALL(Complex112002, pow_112212)(Complex112002 x, NF y) {
	Complex112002 result;
	Complex112002 LOC1;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = complex_112005(y, 0.0);
	result = pow_112201(x, LOC1);
	return result;
}

N_NIMCALL(Complex112002, sin_112217)(Complex112002 z) {
	Complex112002 result;
	NF LOC1;
	NF LOC2;
	NF LOC3;
	NF LOC4;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = 0;
	LOC1 = sin(z.re);
	LOC2 = 0;
	LOC2 = cosh(z.im);
	result.re = ((NF)(LOC1) * (NF)(LOC2));
	LOC3 = 0;
	LOC3 = cos(z.re);
	LOC4 = 0;
	LOC4 = sinh(z.im);
	result.im = ((NF)(LOC3) * (NF)(LOC4));
	return result;
}

N_NIMCALL(Complex112002, arcsin_112221)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	Complex112002 LOC5;
	Complex112002 LOC6;
	Complex112002 LOC7;
	Complex112002 LOC8;
	Complex112002 LOC9;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC2 = HEX2D_112053(LOC1);
	LOC3 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC4 = HEX2A_112072(LOC3, z);
	LOC5 = HEX2A_112072(z, z);
	LOC6 = HEX2D_112057(1.0000000000000000e+00, LOC5);
	LOC7 = sqrt_112171(LOC6);
	LOC8 = HEX2B_112048(LOC4, LOC7);
	LOC9 = ln_112189(LOC8);
	result = HEX2A_112072(LOC2, LOC9);
	return result;
}

N_NIMCALL(Complex112002, cos_112234)(Complex112002 z) {
	Complex112002 result;
	NF LOC1;
	NF LOC2;
	NF LOC3;
	NF LOC4;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = 0;
	LOC1 = cos(z.re);
	LOC2 = 0;
	LOC2 = cosh(z.im);
	result.re = ((NF)(LOC1) * (NF)(LOC2));
	LOC3 = 0;
	LOC3 = sin(z.re);
	LOC4 = 0;
	LOC4 = sinh(z.im);
	result.im = ((NF)(-(LOC3)) * (NF)(LOC4));
	return result;
}

N_NIMCALL(Complex112002, arccos_112238)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	Complex112002 LOC5;
	Complex112002 LOC6;
	Complex112002 LOC7;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC2 = HEX2D_112053(LOC1);
	LOC3 = HEX2A_112072(z, z);
	LOC4 = HEX2D_112062(LOC3, 1.0000000000000000e+00);
	LOC5 = sqrt_112171(LOC4);
	LOC6 = HEX2B_112048(z, LOC5);
	LOC7 = ln_112189(LOC6);
	result = HEX2A_112072(LOC2, LOC7);
	return result;
}

N_NIMCALL(Complex112002, tan_112247)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = sin_112217(z);
	LOC2 = cos_112234(z);
	result = HEX2F_112101(LOC1, LOC2);
	return result;
}

N_NIMCALL(Complex112002, arctan_112251)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	Complex112002 LOC5;
	Complex112002 LOC6;
	Complex112002 LOC7;
	Complex112002 LOC8;
	Complex112002 LOC9;
	Complex112002 LOC10;
	Complex112002 LOC11;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC2 = HEX2A_112077(5.0000000000000000e-01, LOC1);
	LOC3 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC4 = HEX2A_112072(LOC3, z);
	LOC5 = HEX2D_112057(1.0000000000000000e+00, LOC4);
	LOC6 = ln_112189(LOC5);
	LOC7 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC8 = HEX2A_112072(LOC7, z);
	LOC9 = HEX2B_112038(1.0000000000000000e+00, LOC8);
	LOC10 = ln_112189(LOC9);
	LOC11 = HEX2D_112067(LOC6, LOC10);
	result = HEX2A_112072(LOC2, LOC11);
	return result;
}

N_NIMCALL(Complex112002, cot_112270)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = cos_112234(z);
	LOC2 = sin_112217(z);
	result = HEX2F_112101(LOC1, LOC2);
	return result;
}

N_NIMCALL(Complex112002, arccot_112274)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	Complex112002 LOC5;
	Complex112002 LOC6;
	Complex112002 LOC7;
	Complex112002 LOC8;
	Complex112002 LOC9;
	Complex112002 LOC10;
	Complex112002 LOC11;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC2 = HEX2A_112077(5.0000000000000000e-01, LOC1);
	LOC3 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC4 = HEX2F_112101(LOC3, z);
	LOC5 = HEX2D_112057(1.0000000000000000e+00, LOC4);
	LOC6 = ln_112189(LOC5);
	LOC7 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC8 = HEX2F_112101(LOC7, z);
	LOC9 = HEX2B_112038(1.0000000000000000e+00, LOC8);
	LOC10 = ln_112189(LOC9);
	LOC11 = HEX2D_112067(LOC6, LOC10);
	result = HEX2A_112072(LOC2, LOC11);
	return result;
}

N_NIMCALL(Complex112002, sec_112293)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = cos_112234(z);
	result = HEX2F_112096(1.0000000000000000e+00, LOC1);
	return result;
}

N_NIMCALL(Complex112002, arcsec_112298)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	Complex112002 LOC5;
	Complex112002 LOC6;
	Complex112002 LOC7;
	Complex112002 LOC8;
	Complex112002 LOC9;
	Complex112002 LOC10;
	Complex112002 LOC11;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC2 = HEX2D_112053(LOC1);
	LOC3 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC4 = HEX2A_112072(z, z);
	LOC5 = HEX2F_112096(1.0000000000000000e+00, LOC4);
	LOC6 = HEX2D_112057(1.0000000000000000e+00, LOC5);
	LOC7 = sqrt_112171(LOC6);
	LOC8 = HEX2A_112072(LOC3, LOC7);
	LOC9 = HEX2F_112096(1.0000000000000000e+00, z);
	LOC10 = HEX2B_112048(LOC8, LOC9);
	LOC11 = ln_112189(LOC10);
	result = HEX2A_112072(LOC2, LOC11);
	return result;
}

N_NIMCALL(Complex112002, csc_112311)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = sin_112217(z);
	result = HEX2F_112096(1.0000000000000000e+00, LOC1);
	return result;
}

N_NIMCALL(Complex112002, arccsc_112316)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	Complex112002 LOC5;
	Complex112002 LOC6;
	Complex112002 LOC7;
	Complex112002 LOC8;
	Complex112002 LOC9;
	Complex112002 LOC10;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC2 = HEX2D_112053(LOC1);
	LOC3 = HEX2A_112072(z, z);
	LOC4 = HEX2F_112096(1.0000000000000000e+00, LOC3);
	LOC5 = HEX2D_112057(1.0000000000000000e+00, LOC4);
	LOC6 = sqrt_112171(LOC5);
	LOC7 = complex_112005(0.0, 1.0000000000000000e+00);
	LOC8 = HEX2F_112101(LOC7, z);
	LOC9 = HEX2B_112048(LOC6, LOC8);
	LOC10 = ln_112189(LOC9);
	result = HEX2A_112072(LOC2, LOC10);
	return result;
}

N_NIMCALL(Complex112002, sinh_112330)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = exp_112183(z);
	LOC2 = HEX2D_112053(z);
	LOC3 = exp_112183(LOC2);
	LOC4 = HEX2D_112067(LOC1, LOC3);
	result = HEX2A_112077(5.0000000000000000e-01, LOC4);
	return result;
}

N_NIMCALL(Complex112002, arcsinh_112335)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = HEX2A_112072(z, z);
	LOC2 = HEX2B_112043(LOC1, 1.0000000000000000e+00);
	LOC3 = sqrt_112171(LOC2);
	LOC4 = HEX2B_112048(z, LOC3);
	result = ln_112189(LOC4);
	return result;
}

N_NIMCALL(Complex112002, cosh_112339)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = exp_112183(z);
	LOC2 = HEX2D_112053(z);
	LOC3 = exp_112183(LOC2);
	LOC4 = HEX2B_112048(LOC1, LOC3);
	result = HEX2A_112077(5.0000000000000000e-01, LOC4);
	return result;
}

N_NIMCALL(Complex112002, arccosh_112344)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = HEX2A_112072(z, z);
	LOC2 = HEX2D_112062(LOC1, 1.0000000000000000e+00);
	LOC3 = sqrt_112171(LOC2);
	LOC4 = HEX2B_112048(z, LOC3);
	result = ln_112189(LOC4);
	return result;
}

N_NIMCALL(Complex112002, tanh_112349)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = sinh_112330(z);
	LOC2 = cosh_112339(z);
	result = HEX2F_112101(LOC1, LOC2);
	return result;
}

N_NIMCALL(Complex112002, arctanh_112353)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = HEX2B_112038(1.0000000000000000e+00, z);
	LOC2 = HEX2D_112057(1.0000000000000000e+00, z);
	LOC3 = HEX2F_112101(LOC1, LOC2);
	LOC4 = ln_112189(LOC3);
	result = HEX2A_112077(5.0000000000000000e-01, LOC4);
	return result;
}

N_NIMCALL(Complex112002, sech_112360)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = exp_112183(z);
	LOC2 = HEX2D_112053(z);
	LOC3 = exp_112183(LOC2);
	LOC4 = HEX2B_112048(LOC1, LOC3);
	result = HEX2F_112096(2.0000000000000000e+00, LOC4);
	return result;
}

N_NIMCALL(Complex112002, arcsech_112365)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	Complex112002 LOC5;
	Complex112002 LOC6;
	Complex112002 LOC7;
	Complex112002 LOC8;
	Complex112002 LOC9;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = HEX2F_112096(1.0000000000000000e+00, z);
	LOC2 = HEX2F_112096(1.0000000000000000e+00, z);
	LOC3 = HEX2B_112043(LOC2, 1.0000000000000000e+00);
	LOC4 = sqrt_112171(LOC3);
	LOC5 = HEX2F_112096(1.0000000000000000e+00, z);
	LOC6 = HEX2D_112062(LOC5, 1.0000000000000000e+00);
	LOC7 = sqrt_112171(LOC6);
	LOC8 = HEX2A_112072(LOC4, LOC7);
	LOC9 = HEX2B_112048(LOC1, LOC8);
	result = ln_112189(LOC9);
	return result;
}

N_NIMCALL(Complex112002, csch_112373)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = exp_112183(z);
	LOC2 = HEX2D_112053(z);
	LOC3 = exp_112183(LOC2);
	LOC4 = HEX2D_112067(LOC1, LOC3);
	result = HEX2F_112096(2.0000000000000000e+00, LOC4);
	return result;
}

N_NIMCALL(Complex112002, arccsch_112378)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	Complex112002 LOC5;
	Complex112002 LOC6;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = HEX2F_112096(1.0000000000000000e+00, z);
	LOC2 = HEX2A_112072(z, z);
	LOC3 = HEX2F_112096(1.0000000000000000e+00, LOC2);
	LOC4 = HEX2B_112043(LOC3, 1.0000000000000000e+00);
	LOC5 = sqrt_112171(LOC4);
	LOC6 = HEX2B_112048(LOC1, LOC5);
	result = ln_112189(LOC6);
	return result;
}

N_NIMCALL(Complex112002, coth_112385)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = cosh_112339(z);
	LOC2 = sinh_112330(z);
	result = HEX2F_112101(LOC1, LOC2);
	return result;
}

N_NIMCALL(Complex112002, arccoth_112389)(Complex112002 z) {
	Complex112002 result;
	Complex112002 LOC1;
	Complex112002 LOC2;
	Complex112002 LOC3;
	Complex112002 LOC4;
	Complex112002 LOC5;
	Complex112002 LOC6;
	Complex112002 LOC7;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = HEX2F_112096(1.0000000000000000e+00, z);
	LOC2 = HEX2B_112038(1.0000000000000000e+00, LOC1);
	LOC3 = ln_112189(LOC2);
	LOC4 = HEX2F_112096(1.0000000000000000e+00, z);
	LOC5 = HEX2D_112057(1.0000000000000000e+00, LOC4);
	LOC6 = ln_112189(LOC5);
	LOC7 = HEX2D_112067(LOC3, LOC6);
	result = HEX2A_112077(5.0000000000000000e-01, LOC7);
	return result;
}

N_NIMCALL(NF, phase_112398)(Complex112002 z) {
	NF result;
	result = 0;
	result = atan2(z.im, z.re);
	return result;
}

N_NIMCALL(TY112405, polar_112402)(Complex112002 z) {
	TY112405 result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = abs_112021(z);
	result.Field1 = phase_112398(z);
	return result;
}

N_NIMCALL(Complex112002, rect_112412)(NF r, NF phi) {
	Complex112002 result;
	NF LOC1;
	NF LOC2;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = 0;
	LOC1 = cos(phi);
	LOC2 = 0;
	LOC2 = sin(phi);
	result = complex_112005(((NF)(r) * (NF)(LOC1)), ((NF)(r) * (NF)(LOC2)));
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX24_112417)(Complex112002 z) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	result = 0;
	LOC1 = 0;
	LOC2 = 0;
	LOC2 = nimFloatToStr(z.re);
	LOC3 = 0;
	LOC3 = nimFloatToStr(z.im);
	LOC1 = rawNewString(LOC2->Sup.len + LOC3->Sup.len + 4);
appendString(LOC1, ((NimStringDesc*) &TMP263));
appendString(LOC1, LOC2);
appendString(LOC1, ((NimStringDesc*) &TMP264));
appendString(LOC1, LOC3);
appendString(LOC1, ((NimStringDesc*) &TMP265));
	result = LOC1;
	return result;
}

N_NIMCALL(NIM_BOOL, HEX3DHEX7E_112421)(Complex112002 x, Complex112002 y) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("=~", "complex.nim")
	result = 0;
	nimln(325, "complex.nim");
	LOC1 = 0;
	LOC1 = ((((NF)(x.re) - (NF)(y.re)) > 0? (((NF)(x.re) - (NF)(y.re))) : -(((NF)(x.re) - (NF)(y.re)))) < 9.9999999999999995e-07);
	if (!(LOC1)) goto LA2;
	LOC1 = ((((NF)(x.im) - (NF)(y.im)) > 0? (((NF)(x.im) - (NF)(y.im))) : -(((NF)(x.im) - (NF)(y.im)))) < 9.9999999999999995e-07);
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, HEX3DHEX7E_112426)(Complex112002 x, NF y) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("=~", "complex.nim")
	result = 0;
	nimln(328, "complex.nim");
	LOC1 = 0;
	LOC1 = ((((NF)(x.re) - (NF)(y)) > 0? (((NF)(x.re) - (NF)(y))) : -(((NF)(x.re) - (NF)(y)))) < 9.9999999999999995e-07);
	if (!(LOC1)) goto LA2;
	LOC1 = ((x.im > 0? (x.im) : -(x.im)) < 9.9999999999999995e-07);
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_mathDatInit000();
	complexDatInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_mathInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	complexInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, complexInit000)(void) {
	nimfr("complex", "complex.nim")
	nimln(331, "complex.nim");
	z_112431 = complex_112005(0.0, 0.0);
	nimln(332, "complex.nim");
	oo_112432 = complex_112005(1.0000000000000000e+00, 1.0000000000000000e+00);
	nimln(333, "complex.nim");
	a_112433 = complex_112005(1.0000000000000000e+00, 2.0000000000000000e+00);
	nimln(334, "complex.nim");
	b_112436 = complex_112005(-1.0000000000000000e+00, -2.0000000000000000e+00);
	nimln(335, "complex.nim");
	m1_112438 = complex_112005(-1.0000000000000000e+00, 0.0);
	nimln(336, "complex.nim");
	i_112439 = complex_112005(0.0, 1.0000000000000000e+00);
	nimln(337, "complex.nim");
	one_112440 = complex_112005(1.0000000000000000e+00, 0.0);
	nimln(338, "complex.nim");
	tt_112441 = complex_112005(1.0000000000000000e+01, 2.0000000000000000e+01);
	nimln(339, "complex.nim");
	ipi_112443 = complex_112005(0.0, -3.1415926535897931e+00);
	nimln(341, "complex.nim");
	{
		Complex112002 LOC3;
		Complex112002 LOC4;
		NIM_BOOL LOC5;
		LOC3 = HEX2F_112087(a_112433, 2.0000000000000000e+00);
		LOC4 = complex_112005(5.0000000000000000e-01, 1.0000000000000000e+00);
		LOC5 = 0;
		LOC5 = HEX3DHEX7E_112421(LOC3, LOC4);
		if (!!(LOC5)) goto LA6;
		raiseassert_89093(((NimStringDesc*) &TMP266));
	}
	LA6: ;
	nimln(342, "complex.nim");
	{
		NIM_BOOL LOC10;
		LOC10 = 0;
		LOC10 = HEX3DHEX3D_112033(a_112433, a_112433);
		if (!!(LOC10)) goto LA11;
		raiseassert_89093(((NimStringDesc*) &TMP267));
	}
	LA11: ;
	nimln(343, "complex.nim");
	{
		Complex112002 LOC15;
		NIM_BOOL LOC16;
		LOC15 = HEX2D_112067(a_112433, a_112433);
		LOC16 = 0;
		LOC16 = HEX3DHEX3D_112033(LOC15, z_112431);
		if (!!(LOC16)) goto LA17;
		raiseassert_89093(((NimStringDesc*) &TMP268));
	}
	LA17: ;
	nimln(344, "complex.nim");
	{
		Complex112002 LOC21;
		NIM_BOOL LOC22;
		LOC21 = HEX2B_112048(a_112433, b_112436);
		LOC22 = 0;
		LOC22 = HEX3DHEX3D_112033(LOC21, z_112431);
		if (!!(LOC22)) goto LA23;
		raiseassert_89093(((NimStringDesc*) &TMP269));
	}
	LA23: ;
	nimln(345, "complex.nim");
	{
		Complex112002 LOC27;
		NIM_BOOL LOC28;
		LOC27 = HEX2B_112048(a_112433, b_112436);
		LOC28 = 0;
		LOC28 = HEX3DHEX7E_112426(LOC27, 0.0);
		if (!!(LOC28)) goto LA29;
		raiseassert_89093(((NimStringDesc*) &TMP270));
	}
	LA29: ;
	nimln(346, "complex.nim");
	{
		Complex112002 LOC33;
		NIM_BOOL LOC34;
		LOC33 = HEX2F_112101(a_112433, b_112436);
		LOC34 = 0;
		LOC34 = HEX3DHEX3D_112033(LOC33, m1_112438);
		if (!!(LOC34)) goto LA35;
		raiseassert_89093(((NimStringDesc*) &TMP271));
	}
	LA35: ;
	nimln(347, "complex.nim");
	{
		Complex112002 LOC39;
		Complex112002 LOC40;
		NIM_BOOL LOC41;
		LOC39 = HEX2F_112096(1.0000000000000000e+00, a_112433);
		LOC40 = complex_112005(2.0000000000000001e-01, -4.0000000000000002e-01);
		LOC41 = 0;
		LOC41 = HEX3DHEX7E_112421(LOC39, LOC40);
		if (!!(LOC41)) goto LA42;
		raiseassert_89093(((NimStringDesc*) &TMP272));
	}
	LA42: ;
	nimln(348, "complex.nim");
	{
		Complex112002 LOC46;
		Complex112002 LOC47;
		NIM_BOOL LOC48;
		LOC46 = HEX2A_112072(a_112433, b_112436);
		LOC47 = complex_112005(3.0000000000000000e+00, -4.0000000000000000e+00);
		LOC48 = 0;
		LOC48 = HEX3DHEX3D_112033(LOC46, LOC47);
		if (!!(LOC48)) goto LA49;
		raiseassert_89093(((NimStringDesc*) &TMP273));
	}
	LA49: ;
	nimln(349, "complex.nim");
	{
		Complex112002 LOC53;
		NIM_BOOL LOC54;
		LOC53 = HEX2A_112077(1.0000000000000000e+01, a_112433);
		LOC54 = 0;
		LOC54 = HEX3DHEX3D_112033(LOC53, tt_112441);
		if (!!(LOC54)) goto LA55;
		raiseassert_89093(((NimStringDesc*) &TMP274));
	}
	LA55: ;
	nimln(350, "complex.nim");
	{
		Complex112002 LOC59;
		NIM_BOOL LOC60;
		LOC59 = HEX2A_112082(a_112433, 1.0000000000000000e+01);
		LOC60 = 0;
		LOC60 = HEX3DHEX3D_112033(LOC59, tt_112441);
		if (!!(LOC60)) goto LA61;
		raiseassert_89093(((NimStringDesc*) &TMP275));
	}
	LA61: ;
	nimln(351, "complex.nim");
	{
		Complex112002 LOC65;
		NIM_BOOL LOC66;
		LOC65 = HEX2F_112087(tt_112441, 1.0000000000000000e+01);
		LOC66 = 0;
		LOC66 = HEX3DHEX3D_112033(LOC65, a_112433);
		if (!!(LOC66)) goto LA67;
		raiseassert_89093(((NimStringDesc*) &TMP276));
	}
	LA67: ;
	nimln(352, "complex.nim");
	{
		Complex112002 LOC71;
		NIM_BOOL LOC72;
		LOC71 = HEX2B_112043(oo_112432, -1.0000000000000000e+00);
		LOC72 = 0;
		LOC72 = HEX3DHEX3D_112033(LOC71, i_112439);
		if (!!(LOC72)) goto LA73;
		raiseassert_89093(((NimStringDesc*) &TMP277));
	}
	LA73: ;
	nimln(353, "complex.nim");
	{
		Complex112002 LOC77;
		NIM_BOOL LOC78;
		LOC77 = HEX2B_112038(-1.0000000000000000e+00, oo_112432);
		LOC78 = 0;
		LOC78 = HEX3DHEX3D_112033(LOC77, i_112439);
		if (!!(LOC78)) goto LA79;
		raiseassert_89093(((NimStringDesc*) &TMP278));
	}
	LA79: ;
	nimln(354, "complex.nim");
	{
		NF LOC83;
		NF LOC84;
		LOC83 = 0;
		LOC83 = abs_112021(oo_112432);
		LOC84 = 0;
		LOC84 = sqrt(2.0000000000000000e+00);
		if (!!((LOC83 == LOC84))) goto LA85;
		raiseassert_89093(((NimStringDesc*) &TMP279));
	}
	LA85: ;
	nimln(355, "complex.nim");
	{
		Complex112002 LOC89;
		Complex112002 LOC90;
		NIM_BOOL LOC91;
		LOC89 = conjugate_112029(a_112433);
		LOC90 = complex_112005(1.0000000000000000e+00, -2.0000000000000000e+00);
		LOC91 = 0;
		LOC91 = HEX3DHEX3D_112033(LOC89, LOC90);
		if (!!(LOC91)) goto LA92;
		raiseassert_89093(((NimStringDesc*) &TMP280));
	}
	LA92: ;
	nimln(356, "complex.nim");
	{
		Complex112002 LOC96;
		NIM_BOOL LOC97;
		LOC96 = sqrt_112171(m1_112438);
		LOC97 = 0;
		LOC97 = HEX3DHEX3D_112033(LOC96, i_112439);
		if (!!(LOC97)) goto LA98;
		raiseassert_89093(((NimStringDesc*) &TMP281));
	}
	LA98: ;
	nimln(357, "complex.nim");
	{
		Complex112002 LOC102;
		NIM_BOOL LOC103;
		LOC102 = exp_112183(ipi_112443);
		LOC103 = 0;
		LOC103 = HEX3DHEX7E_112421(LOC102, m1_112438);
		if (!!(LOC103)) goto LA104;
		raiseassert_89093(((NimStringDesc*) &TMP282));
	}
	LA104: ;
	nimln(359, "complex.nim");
	{
		Complex112002 LOC108;
		Complex112002 LOC109;
		NIM_BOOL LOC110;
		LOC108 = pow_112201(a_112433, b_112436);
		LOC109 = complex_112005(-3.7299912492787599e+00, -1.6881582672506801e+00);
		LOC110 = 0;
		LOC110 = HEX3DHEX7E_112421(LOC108, LOC109);
		if (!!(LOC110)) goto LA111;
		raiseassert_89093(((NimStringDesc*) &TMP283));
	}
	LA111: ;
	nimln(360, "complex.nim");
	{
		Complex112002 LOC115;
		Complex112002 LOC116;
		NIM_BOOL LOC117;
		LOC115 = pow_112201(z_112431, a_112433);
		LOC116 = complex_112005(0.0, 0.0);
		LOC117 = 0;
		LOC117 = HEX3DHEX7E_112421(LOC115, LOC116);
		if (!!(LOC117)) goto LA118;
		raiseassert_89093(((NimStringDesc*) &TMP284));
	}
	LA118: ;
	nimln(361, "complex.nim");
	{
		Complex112002 LOC122;
		Complex112002 LOC123;
		NIM_BOOL LOC124;
		LOC122 = pow_112201(z_112431, z_112431);
		LOC123 = complex_112005(1.0000000000000000e+00, 0.0);
		LOC124 = 0;
		LOC124 = HEX3DHEX7E_112421(LOC122, LOC123);
		if (!!(LOC124)) goto LA125;
		raiseassert_89093(((NimStringDesc*) &TMP285));
	}
	LA125: ;
	nimln(362, "complex.nim");
	{
		Complex112002 LOC129;
		NIM_BOOL LOC130;
		LOC129 = pow_112201(a_112433, one_112440);
		LOC130 = 0;
		LOC130 = HEX3DHEX7E_112421(LOC129, a_112433);
		if (!!(LOC130)) goto LA131;
		raiseassert_89093(((NimStringDesc*) &TMP286));
	}
	LA131: ;
	nimln(363, "complex.nim");
	{
		Complex112002 LOC135;
		Complex112002 LOC136;
		NIM_BOOL LOC137;
		LOC135 = pow_112201(a_112433, m1_112438);
		LOC136 = complex_112005(2.0000000000000001e-01, -4.0000000000000002e-01);
		LOC137 = 0;
		LOC137 = HEX3DHEX7E_112421(LOC135, LOC136);
		if (!!(LOC137)) goto LA138;
		raiseassert_89093(((NimStringDesc*) &TMP287));
	}
	LA138: ;
	nimln(364, "complex.nim");
	{
		Complex112002 LOC142;
		Complex112002 LOC143;
		NIM_BOOL LOC144;
		LOC142 = pow_112212(a_112433, 2.0000000000000000e+00);
		LOC143 = complex_112005(-3.0000000000000000e+00, 4.0000000000000000e+00);
		LOC144 = 0;
		LOC144 = HEX3DHEX7E_112421(LOC142, LOC143);
		if (!!(LOC144)) goto LA145;
		raiseassert_89093(((NimStringDesc*) &TMP288));
	}
	LA145: ;
	nimln(365, "complex.nim");
	{
		Complex112002 LOC149;
		Complex112002 LOC150;
		NIM_BOOL LOC151;
		LOC149 = pow_112212(a_112433, 2.0000000000000000e+00);
		LOC150 = complex_112005(-3.0000000000000000e+00, 4.0000000000000000e+00);
		LOC151 = 0;
		LOC151 = HEX3DHEX7E_112421(LOC149, LOC150);
		if (!!(LOC151)) goto LA152;
		raiseassert_89093(((NimStringDesc*) &TMP289));
	}
	LA152: ;
	nimln(366, "complex.nim");
	{
		Complex112002 LOC156;
		NIM_BOOL LOC157;
		LOC156 = pow_112212(a_112433, 2.0000000000000000e+00);
		LOC157 = 0;
		LOC157 = HEX3DHEX7E_112421(LOC156, a_112433);
		if (!!(!(LOC157))) goto LA158;
		raiseassert_89093(((NimStringDesc*) &TMP290));
	}
	LA158: ;
	nimln(368, "complex.nim");
	{
		Complex112002 LOC162;
		Complex112002 LOC163;
		NIM_BOOL LOC164;
		LOC162 = ln_112189(a_112433);
		LOC163 = complex_112005(8.0471895621705003e-01, 1.1071487177940900e+00);
		LOC164 = 0;
		LOC164 = HEX3DHEX7E_112421(LOC162, LOC163);
		if (!!(LOC164)) goto LA165;
		raiseassert_89093(((NimStringDesc*) &TMP291));
	}
	LA165: ;
	nimln(369, "complex.nim");
	{
		Complex112002 LOC169;
		Complex112002 LOC170;
		NIM_BOOL LOC171;
		LOC169 = log10_112193(a_112433);
		LOC170 = complex_112005(3.4948500216800898e-01, 4.8082857878423402e-01);
		LOC171 = 0;
		LOC171 = HEX3DHEX7E_112421(LOC169, LOC170);
		if (!!(LOC171)) goto LA172;
		raiseassert_89093(((NimStringDesc*) &TMP292));
	}
	LA172: ;
	nimln(370, "complex.nim");
	{
		Complex112002 LOC176;
		Complex112002 LOC177;
		NIM_BOOL LOC178;
		LOC176 = log2_112197(a_112433);
		LOC177 = complex_112005(1.1609640474436800e+00, 1.5972779646881099e+00);
		LOC178 = 0;
		LOC178 = HEX3DHEX7E_112421(LOC176, LOC177);
		if (!!(LOC178)) goto LA179;
		raiseassert_89093(((NimStringDesc*) &TMP293));
	}
	LA179: ;
	nimln(372, "complex.nim");
	{
		Complex112002 LOC183;
		Complex112002 LOC184;
		NIM_BOOL LOC185;
		LOC183 = sin_112217(a_112433);
		LOC184 = complex_112005(3.1657785132161700e+00, 1.9596010414216101e+00);
		LOC185 = 0;
		LOC185 = HEX3DHEX7E_112421(LOC183, LOC184);
		if (!!(LOC185)) goto LA186;
		raiseassert_89093(((NimStringDesc*) &TMP294));
	}
	LA186: ;
	nimln(373, "complex.nim");
	{
		Complex112002 LOC190;
		Complex112002 LOC191;
		NIM_BOOL LOC192;
		LOC190 = cos_112234(a_112433);
		LOC191 = complex_112005(2.0327230070196700e+00, -3.0518977991518002e+00);
		LOC192 = 0;
		LOC192 = HEX3DHEX7E_112421(LOC190, LOC191);
		if (!!(LOC192)) goto LA193;
		raiseassert_89093(((NimStringDesc*) &TMP295));
	}
	LA193: ;
	nimln(374, "complex.nim");
	{
		Complex112002 LOC197;
		Complex112002 LOC198;
		NIM_BOOL LOC199;
		LOC197 = tan_112247(a_112433);
		LOC198 = complex_112005(3.3812826079896698e-02, 1.0147936161466335e+00);
		LOC199 = 0;
		LOC199 = HEX3DHEX7E_112421(LOC197, LOC198);
		if (!!(LOC199)) goto LA200;
		raiseassert_89093(((NimStringDesc*) &TMP296));
	}
	LA200: ;
	nimln(375, "complex.nim");
	{
		Complex112002 LOC204;
		Complex112002 LOC205;
		Complex112002 LOC206;
		NIM_BOOL LOC207;
		LOC204 = cot_112270(a_112433);
		LOC205 = tan_112247(a_112433);
		LOC206 = HEX2F_112096(1.0000000000000000e+00, LOC205);
		LOC207 = 0;
		LOC207 = HEX3DHEX7E_112421(LOC204, LOC206);
		if (!!(LOC207)) goto LA208;
		raiseassert_89093(((NimStringDesc*) &TMP297));
	}
	LA208: ;
	nimln(376, "complex.nim");
	{
		Complex112002 LOC212;
		Complex112002 LOC213;
		Complex112002 LOC214;
		NIM_BOOL LOC215;
		LOC212 = sec_112293(a_112433);
		LOC213 = cos_112234(a_112433);
		LOC214 = HEX2F_112096(1.0000000000000000e+00, LOC213);
		LOC215 = 0;
		LOC215 = HEX3DHEX7E_112421(LOC212, LOC214);
		if (!!(LOC215)) goto LA216;
		raiseassert_89093(((NimStringDesc*) &TMP298));
	}
	LA216: ;
	nimln(377, "complex.nim");
	{
		Complex112002 LOC220;
		Complex112002 LOC221;
		Complex112002 LOC222;
		NIM_BOOL LOC223;
		LOC220 = csc_112311(a_112433);
		LOC221 = sin_112217(a_112433);
		LOC222 = HEX2F_112096(1.0000000000000000e+00, LOC221);
		LOC223 = 0;
		LOC223 = HEX3DHEX7E_112421(LOC220, LOC222);
		if (!!(LOC223)) goto LA224;
		raiseassert_89093(((NimStringDesc*) &TMP299));
	}
	LA224: ;
	nimln(378, "complex.nim");
	{
		Complex112002 LOC228;
		Complex112002 LOC229;
		NIM_BOOL LOC230;
		LOC228 = arcsin_112221(a_112433);
		LOC229 = complex_112005(4.2707858639247598e-01, 1.5285709194809980e+00);
		LOC230 = 0;
		LOC230 = HEX3DHEX7E_112421(LOC228, LOC229);
		if (!!(LOC230)) goto LA231;
		raiseassert_89093(((NimStringDesc*) &TMP300));
	}
	LA231: ;
	nimln(379, "complex.nim");
	{
		Complex112002 LOC235;
		Complex112002 LOC236;
		NIM_BOOL LOC237;
		LOC235 = arccos_112238(a_112433);
		LOC236 = complex_112005(1.1437177404024199e+00, -1.5285709194810000e+00);
		LOC237 = 0;
		LOC237 = HEX3DHEX7E_112421(LOC235, LOC236);
		if (!!(LOC237)) goto LA238;
		raiseassert_89093(((NimStringDesc*) &TMP301));
	}
	LA238: ;
	nimln(380, "complex.nim");
	{
		Complex112002 LOC242;
		Complex112002 LOC243;
		NIM_BOOL LOC244;
		LOC242 = arctan_112251(a_112433);
		LOC243 = complex_112005(1.3389725222944939e+00, 4.0235947810852501e-01);
		LOC244 = 0;
		LOC244 = HEX3DHEX7E_112421(LOC242, LOC243);
		if (!!(LOC244)) goto LA245;
		raiseassert_89093(((NimStringDesc*) &TMP302));
	}
	LA245: ;
	nimln(381, "complex.nim");
	{
		Complex112002 LOC249;
		Complex112002 LOC250;
		NIM_BOOL LOC251;
		LOC249 = arccot_112274(a_112433);
		LOC250 = complex_112005(2.3182380450040310e-01, -4.0235947810852501e-01);
		LOC251 = 0;
		LOC251 = HEX3DHEX7E_112421(LOC249, LOC250);
		if (!!(LOC251)) goto LA252;
		raiseassert_89093(((NimStringDesc*) &TMP303));
	}
	LA252: ;
	nimln(382, "complex.nim");
	{
		Complex112002 LOC256;
		Complex112002 LOC257;
		NIM_BOOL LOC258;
		LOC256 = arcsec_112298(a_112433);
		LOC257 = complex_112005(1.3844782726870810e+00, 3.9656823011232878e-01);
		LOC258 = 0;
		LOC258 = HEX3DHEX7E_112421(LOC256, LOC257);
		if (!!(LOC258)) goto LA259;
		raiseassert_89093(((NimStringDesc*) &TMP304));
	}
	LA259: ;
	nimln(383, "complex.nim");
	{
		Complex112002 LOC263;
		Complex112002 LOC264;
		NIM_BOOL LOC265;
		LOC263 = arccsc_112316(a_112433);
		LOC264 = complex_112005(1.8631805410781549e-01, -3.9656823011232911e-01);
		LOC265 = 0;
		LOC265 = HEX3DHEX7E_112421(LOC263, LOC264);
		if (!!(LOC265)) goto LA266;
		raiseassert_89093(((NimStringDesc*) &TMP305));
	}
	LA266: ;
	nimln(385, "complex.nim");
	{
		Complex112002 LOC270;
		Complex112002 LOC271;
		NIM_BOOL LOC272;
		LOC270 = cosh_112339(a_112433);
		LOC271 = complex_112005(-6.4214812471551996e-01, 1.0686074213827781e+00);
		LOC272 = 0;
		LOC272 = HEX3DHEX7E_112421(LOC270, LOC271);
		if (!!(LOC272)) goto LA273;
		raiseassert_89093(((NimStringDesc*) &TMP306));
	}
	LA273: ;
	nimln(386, "complex.nim");
	{
		Complex112002 LOC277;
		Complex112002 LOC278;
		NIM_BOOL LOC279;
		LOC277 = sinh_112330(a_112433);
		LOC278 = complex_112005(-4.8905625904129402e-01, 1.4031192506220400e+00);
		LOC279 = 0;
		LOC279 = HEX3DHEX7E_112421(LOC277, LOC278);
		if (!!(LOC279)) goto LA280;
		raiseassert_89093(((NimStringDesc*) &TMP307));
	}
	LA280: ;
	nimln(387, "complex.nim");
	{
		Complex112002 LOC284;
		Complex112002 LOC285;
		NIM_BOOL LOC286;
		LOC284 = tanh_112349(a_112433);
		LOC285 = complex_112005(1.1667362572409199e+00, -2.4345820118572500e-01);
		LOC286 = 0;
		LOC286 = HEX3DHEX7E_112421(LOC284, LOC285);
		if (!!(LOC286)) goto LA287;
		raiseassert_89093(((NimStringDesc*) &TMP308));
	}
	LA287: ;
	nimln(388, "complex.nim");
	{
		Complex112002 LOC291;
		Complex112002 LOC292;
		Complex112002 LOC293;
		NIM_BOOL LOC294;
		LOC291 = sech_112360(a_112433);
		LOC292 = cosh_112339(a_112433);
		LOC293 = HEX2F_112096(1.0000000000000000e+00, LOC292);
		LOC294 = 0;
		LOC294 = HEX3DHEX7E_112421(LOC291, LOC293);
		if (!!(LOC294)) goto LA295;
		raiseassert_89093(((NimStringDesc*) &TMP309));
	}
	LA295: ;
	nimln(389, "complex.nim");
	{
		Complex112002 LOC299;
		Complex112002 LOC300;
		Complex112002 LOC301;
		NIM_BOOL LOC302;
		LOC299 = csch_112373(a_112433);
		LOC300 = sinh_112330(a_112433);
		LOC301 = HEX2F_112096(1.0000000000000000e+00, LOC300);
		LOC302 = 0;
		LOC302 = HEX3DHEX7E_112421(LOC299, LOC301);
		if (!!(LOC302)) goto LA303;
		raiseassert_89093(((NimStringDesc*) &TMP310));
	}
	LA303: ;
	nimln(390, "complex.nim");
	{
		Complex112002 LOC307;
		Complex112002 LOC308;
		Complex112002 LOC309;
		NIM_BOOL LOC310;
		LOC307 = coth_112385(a_112433);
		LOC308 = tanh_112349(a_112433);
		LOC309 = HEX2F_112096(1.0000000000000000e+00, LOC308);
		LOC310 = 0;
		LOC310 = HEX3DHEX7E_112421(LOC307, LOC309);
		if (!!(LOC310)) goto LA311;
		raiseassert_89093(((NimStringDesc*) &TMP311));
	}
	LA311: ;
	nimln(391, "complex.nim");
	{
		Complex112002 LOC315;
		Complex112002 LOC316;
		NIM_BOOL LOC317;
		LOC315 = arccosh_112344(a_112433);
		LOC316 = complex_112005(1.5285709194809980e+00, 1.1437177404024199e+00);
		LOC317 = 0;
		LOC317 = HEX3DHEX7E_112421(LOC315, LOC316);
		if (!!(LOC317)) goto LA318;
		raiseassert_89093(((NimStringDesc*) &TMP312));
	}
	LA318: ;
	nimln(392, "complex.nim");
	{
		Complex112002 LOC322;
		Complex112002 LOC323;
		NIM_BOOL LOC324;
		LOC322 = arcsinh_112335(a_112433);
		LOC323 = complex_112005(1.4693517443681849e+00, 1.0634400235777499e+00);
		LOC324 = 0;
		LOC324 = HEX3DHEX7E_112421(LOC322, LOC323);
		if (!!(LOC324)) goto LA325;
		raiseassert_89093(((NimStringDesc*) &TMP313));
	}
	LA325: ;
	nimln(393, "complex.nim");
	{
		Complex112002 LOC329;
		Complex112002 LOC330;
		NIM_BOOL LOC331;
		LOC329 = arctanh_112353(a_112433);
		LOC330 = complex_112005(1.7328679513998599e-01, 1.1780972450961700e+00);
		LOC331 = 0;
		LOC331 = HEX3DHEX7E_112421(LOC329, LOC330);
		if (!!(LOC331)) goto LA332;
		raiseassert_89093(((NimStringDesc*) &TMP314));
	}
	LA332: ;
	nimln(394, "complex.nim");
	{
		Complex112002 LOC336;
		Complex112002 LOC337;
		Complex112002 LOC338;
		NIM_BOOL LOC339;
		LOC336 = arcsech_112365(a_112433);
		LOC337 = HEX2F_112096(1.0000000000000000e+00, a_112433);
		LOC338 = arccosh_112344(LOC337);
		LOC339 = 0;
		LOC339 = HEX3DHEX7E_112421(LOC336, LOC338);
		if (!!(LOC339)) goto LA340;
		raiseassert_89093(((NimStringDesc*) &TMP315));
	}
	LA340: ;
	nimln(395, "complex.nim");
	{
		Complex112002 LOC344;
		Complex112002 LOC345;
		Complex112002 LOC346;
		NIM_BOOL LOC347;
		LOC344 = arccsch_112378(a_112433);
		LOC345 = HEX2F_112096(1.0000000000000000e+00, a_112433);
		LOC346 = arcsinh_112335(LOC345);
		LOC347 = 0;
		LOC347 = HEX3DHEX7E_112421(LOC344, LOC346);
		if (!!(LOC347)) goto LA348;
		raiseassert_89093(((NimStringDesc*) &TMP316));
	}
	LA348: ;
	nimln(396, "complex.nim");
	{
		Complex112002 LOC352;
		Complex112002 LOC353;
		Complex112002 LOC354;
		NIM_BOOL LOC355;
		LOC352 = arccoth_112389(a_112433);
		LOC353 = HEX2F_112096(1.0000000000000000e+00, a_112433);
		LOC354 = arctanh_112353(LOC353);
		LOC355 = 0;
		LOC355 = HEX3DHEX7E_112421(LOC352, LOC354);
		if (!!(LOC355)) goto LA356;
		raiseassert_89093(((NimStringDesc*) &TMP317));
	}
	LA356: ;
	nimln(398, "complex.nim");
	{
		NF LOC360;
		LOC360 = 0;
		LOC360 = phase_112398(a_112433);
		if (!!((LOC360 == 1.1071487177940904e+00))) goto LA361;
		raiseassert_89093(((NimStringDesc*) &TMP318));
	}
	LA361: ;
	nimln(399, "complex.nim");
	t_112461 = polar_112402(a_112433);
	nimln(400, "complex.nim");
	{
		Complex112002 LOC365;
		NIM_BOOL LOC366;
		LOC365 = rect_112412(t_112461.Field0, t_112461.Field1);
		LOC366 = 0;
		LOC366 = HEX3DHEX7E_112421(LOC365, a_112433);
		if (!!(LOC366)) goto LA367;
		raiseassert_89093(((NimStringDesc*) &TMP319));
	}
	LA367: ;
	nimln(401, "complex.nim");
	{
		Complex112002 LOC371;
		Complex112002 LOC372;
		NIM_BOOL LOC373;
		LOC371 = rect_112412(1.0000000000000000e+00, 2.0000000000000000e+00);
		LOC372 = complex_112005(-4.1614683654714241e-01, 9.0929742682568171e-01);
		LOC373 = 0;
		LOC373 = HEX3DHEX7E_112421(LOC371, LOC372);
		if (!!(LOC373)) goto LA374;
		raiseassert_89093(((NimStringDesc*) &TMP320));
	}
	LA374: ;
	nimln(405, "complex.nim");
	{
		if (!!((((NI)sizeof(Complex112002)) == ((NI) 16)))) goto LA378;
		raiseassert_89093(((NimStringDesc*) &TMP321));
	}
	LA378: ;
	nimln(407, "complex.nim");
	{
		Complex112002 LOC382;
		Complex112002 LOC383;
		Complex112002 LOC384;
		NIM_BOOL LOC385;
		LOC382 = complex_112005(0.0, 1.2300000000000000e+02);
		LOC383 = HEX2B_112043(LOC382, 4.5600000000000000e+02);
		LOC384 = complex_112005(4.5600000000000000e+02, 1.2300000000000000e+02);
		LOC385 = 0;
		LOC385 = HEX3DHEX3D_112033(LOC383, LOC384);
		if (!!(LOC385)) goto LA386;
		raiseassert_89093(((NimStringDesc*) &TMP322));
	}
	LA386: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, complexDatInit000)(void) {
}

