/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/chaemon/.choosenim/toolchains/nim-0.13.0/lib -o /home/chaemon/git/library-1/nim/other/nimcache/compress.o /home/chaemon/git/library-1/nim/other/nimcache/compress.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
typedef struct TY94089 TY94089;
typedef struct TGenericSeq TGenericSeq;
typedef struct Compress94094 Compress94094;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  Compress94094  {
TY94089* xs;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef struct {
N_NIMCALL_PTR(NI, ClPrc) (NI x_94155, NI y_94157, void* ClEnv);
void* ClEnv;
} TY94153;
typedef N_CLOSURE_PTR(NI, TMP167) (NI x_94142, NI y_94144, void* ClEnv);
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY94089 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, newcompless_94086)(TY94089* xs, Compress94094* Result);
N_NIMCALL(void, TMP146)(void* p, NI op);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_84404, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, build_94120)(Compress94094* self);
N_NIMCALL(void, sort_94146)(NI* a, NI aLen0, TY94153 cmp, NU8 order);
N_NIMCALL(NI, cmp_94132)(NI x, NI y);
N_NIMCALL(TY94089*, deduplicate_95636)(TY94089* seq1);
N_NIMCALL(void, merge_94191)(NI* a, NI aLen0, NI* b, NI bLen0, NI lo, NI m, NI hi, TY94153 cmp, NU8 order);
static N_INLINE(NIM_BOOL, contains_95805)(NI* a, NI aLen0, NI item);
static N_INLINE(NI, find_95815)(NI* a, NI aLen0, NI item);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, HEX5BHEX5D_95881)(Compress94094 self, NI k);
N_NIMCALL(TY94089*, get_95907)(Compress94094 self, TY94089* v);
N_NIMCALL(TY94089*, newseq_95918)(NI len);
N_NIMCALL(NI, get_95945)(Compress94094 self, NI t);
N_NIMCALL(NI, lowerbound_95957)(NI* a, NI aLen0, NI key);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, failedassertimpl_89116)(NimStringDesc* msg);
N_NIMCALL(NI, lowerbound_95983)(NI* a, NI aLen0, NI key, TY94153 cmp);
N_NIMCALL(NimStringDesc*, HEX24_96052)(TY94089* x);
N_NIMCALL(NimStringDesc*, collectiontostring_96060)(TY94089* x, NimStringDesc* b, NimStringDesc* e);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, compressInit000)(void);
NIM_EXTERNC N_NOINLINE(void, compressDatInit000)(void);
STRING_LITERAL(TMP184, "len(a) == L seq modified while iterating over it", 48);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[5];
} CNSTSEQ190 = {{5, 5}, {((NI) 10),
((NI) 1),
((NI) 100),
((NI) 1000),
((NI) 12)}};
NIM_CONST TY94089* TMP188 = ((TY94089*)&CNSTSEQ190);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[4];
} CNSTSEQ192 = {{4, 4}, {((NI) 1),
((NI) 10),
((NI) 100),
((NI) 12)}};
NIM_CONST TY94089* TMP190 = ((TY94089*)&CNSTSEQ192);
extern TNimType NTI104; /* int */
TNimType NTI94089; /* seq[int] */
extern TFrame* frameptr_19436;
Compress94094 c_94118;
TNimType NTI94094; /* Compress */
N_NIMCALL(void, TMP146)(void* p, NI op) {
	TY94089* a;
	NI LOC1;
	a = (TY94089*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(void, newcompless_94086)(TY94089* xs, Compress94094* Result) {
	Compress94094 LOC1;
	nimfr("newCompless", "compress.nim")
{	nimln(8, "compress.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	genericSeqAssign((&LOC1.xs), xs, (&NTI94089));
	unsureAsgnRef((void**) (&(*Result).xs), LOC1.xs);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, build_94120)(Compress94094* self) {
	TY94153 LOC1;
	nimfr("build", "compress.nim")
	nimln(16, "compress.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = ((TMP167) (cmp_94132)); LOC1.ClEnv = NIM_NIL;
	sort_94146((*self).xs->data, (*self).xs->Sup.len, LOC1, ((NU8) 1));
	nimln(17, "compress.nim");
	unsureAsgnRef((void**) (&(*self).xs), deduplicate_95636((*self).xs));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, find_95815)(NI* a, NI aLen0, NI item) {
	NI result;
	nimfr("find", "system.nim")
{	result = 0;
	{
		NI i_95849;
		NI i_95862;
		i_95849 = 0;
		nimln(1965, "system.nim");
		i_95862 = ((NI) 0);
		{
			nimln(1966, "system.nim");
			while (1) {
				NI TMP172;
				NI TMP173;
				if (!(i_95862 < aLen0)) goto LA3;
				nimln(1967, "system.nim");
				if ((NU)(i_95862) >= (NU)(aLen0)) raiseIndexError();
				i_95849 = a[i_95862];
				nimln(2190, "system.nim");
				{
					if (!(i_95849 == item)) goto LA6;
					goto BeforeRet;
				}
				LA6: ;
				nimln(2191, "system.nim");
				TMP172 = addInt(result, ((NI) 1));
				result = (NI)(TMP172);
				nimln(1968, "system.nim");
				TMP173 = addInt(i_95862, ((NI) 1));
				i_95862 = (NI)(TMP173);
			} LA3: ;
		}
	}
	nimln(2192, "system.nim");
	result = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_95805)(NI* a, NI aLen0, NI item) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("contains", "system.nim")
{	result = 0;
	nimln(2197, "system.nim");
	nimln(352, "system.nim");
	nimln(353, "system.nim");
	nimln(2197, "system.nim");
	LOC1 = 0;
	LOC1 = find_95815(a, aLen0, item);
	result = (((NI) 0) <= LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, HEX5BHEX5D_95881)(Compress94094 self, NI k) {
	NI result;
	nimfr("[]", "compress.nim")
{	result = 0;
	nimln(25, "compress.nim");
	if ((NU)(k) >= (NU)(self.xs->Sup.len)) raiseIndexError();
	result = self.xs->data[k];
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, get_95945)(Compress94094 self, NI t) {
	NI result;
	nimfr("get", "compress.nim")
{	result = 0;
	nimln(20, "compress.nim");
	result = lowerbound_95957(self.xs->data, self.xs->Sup.len, t);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(TY94089*, get_95907)(Compress94094 self, TY94089* v) {
	TY94089* result;
	nimfr("get", "compress.nim")
	result = 0;
	nimln(22, "compress.nim");
	result = newseq_95918(((NI) 0));
	{
		NI t_95943;
		NI i_96048;
		NI L_96050;
		t_95943 = 0;
		nimln(3361, "system.nim");
		i_96048 = ((NI) 0);
		nimln(3362, "system.nim");
		L_96050 = (v ? v->Sup.len : 0);
		{
			nimln(3363, "system.nim");
			while (1) {
				NI LOC4;
				NI TMP183;
				if (!(i_96048 < L_96050)) goto LA3;
				nimln(3364, "system.nim");
				if ((NU)(i_96048) >= (NU)(v->Sup.len)) raiseIndexError();
				t_95943 = v->data[i_96048];
				nimln(23, "compress.nim");
				LOC4 = 0;
				LOC4 = get_95945(self, t_95943);
				result = (TY94089*) incrSeqV2(&(result)->Sup, sizeof(NI));
				result->data[result->Sup.len] = LOC4;
				++result->Sup.len;
				nimln(3365, "system.nim");
				TMP183 = addInt(i_96048, ((NI) 1));
				i_96048 = (NI)(TMP183);
				nimln(3366, "system.nim");
				{
					if (!!(((v ? v->Sup.len : 0) == L_96050))) goto LA7;
					failedassertimpl_89116(((NimStringDesc*) &TMP184));
				}
				LA7: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_sequtilsDatInit000();
	stdlib_algorithmDatInit000();
	compressDatInit000();
	stdlib_sequtilsInit000();
	stdlib_algorithmInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	compressInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, compressInit000)(void) {
	nimfr("compress", "compress.nim")
	nimln(27, "compress.nim");
	{
		NI LOC5;
		NimStringDesc* LOC6;
		TY94089* LOC7;
		NimStringDesc* LOC8;
		if (!NIM_TRUE) goto LA3;
		nimln(28, "compress.nim");
		chckNil((void*)(&c_94118));
		genericReset((void*)(&c_94118), (&NTI94094));
		newcompless_94086(TMP188, (&c_94118));
		nimln(29, "compress.nim");
		build_94120((&c_94118));
		nimln(30, "compress.nim");
		LOC5 = 0;
		LOC5 = HEX5BHEX5D_95881(c_94118, ((NI) 2));
		LOC6 = 0;
		LOC6 = nimIntToStr(LOC5);
		printf("%s\012", LOC6? (LOC6)->data:"nil");
		fflush(stdout);
		nimln(31, "compress.nim");
		LOC7 = 0;
		LOC7 = get_95907(c_94118, TMP190);
		LOC8 = 0;
		LOC8 = HEX24_96052(LOC7);
		printf("%s\012", LOC8? (LOC8)->data:"nil");
		fflush(stdout);
	}
	LA3: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, compressDatInit000)(void) {
static TNimNode TMP138[1];
NTI94089.size = sizeof(TY94089*);
NTI94089.kind = 24;
NTI94089.base = (&NTI104);
NTI94089.flags = 2;
NTI94089.marker = TMP146;
NTI94094.size = sizeof(Compress94094);
NTI94094.kind = 18;
NTI94094.base = 0;
NTI94094.flags = 2;
TMP138[0].kind = 1;
TMP138[0].offset = offsetof(Compress94094, xs);
TMP138[0].typ = (&NTI94089);
TMP138[0].name = "xs";
NTI94094.node = &TMP138[0];
}

