/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/chaemon/.choosenim/toolchains/nim-0.13.0/lib -o /home/chaemon/git/library-1/nim/other/nimcache/stdlib_algorithm.o /home/chaemon/git/library-1/nim/other/nimcache/stdlib_algorithm.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct TY94089 TY94089;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct {
N_NIMCALL_PTR(NI, ClPrc) (NI x_94155, NI y_94157, void* ClEnv);
void* ClEnv;
} TY94153;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CLOSURE_PTR(NI, TMP151) (NI x_94210, NI y_94212);
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CLOSURE_PTR(NI, TMP155) (NI x_94210, NI y_94212);
typedef N_CLOSURE_PTR(NI, TMP178) (NI x_95993, NI y_95995);
typedef N_CLOSURE_PTR(NI, TMP182) (NI x_95979, NI y_95981, void* ClEnv);
struct TY94089 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, HEX2A_93008)(NI x, NU8 order);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, merge_94191)(NI* a, NI aLen0, NI* b, NI bLen0, NI lo, NI m, NI hi, TY94153 cmp, NU8 order);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, failedassertimpl_89116)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(NI, lowerbound_95983)(NI* a, NI aLen0, NI key, TY94153 cmp);
N_NIMCALL(NI, cmp_94132)(NI x, NI y);
STRING_LITERAL(TMP152, "j <= m ", 7);
extern TFrame* frameptr_19436;
extern TNimType NTI94089; /* seq[int] */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(NI, HEX2A_93008)(NI x, NU8 order) {
	NI result;
	NI y;
	NI TMP144;
	NI TMP145;
	nimfr("*", "algorithm.nim")
	result = 0;
	nimln(24, "algorithm.nim");
	TMP144 = subInt(((NI) (order)), ((NI) 1));
	y = (NI)(TMP144);
	nimln(25, "algorithm.nim");
	TMP145 = subInt((NI)(x ^ ((NI) (y))), ((NI) (y)));
	result = (NI)(TMP145);
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, merge_94191)(NI* a, NI aLen0, NI* b, NI bLen0, NI lo, NI m, NI hi, TY94153 cmp, NU8 order) {
	NI j;
	NI bb;
	NI i;
	NI k;
	nimfr("merge", "algorithm.nim")
{	nimln(128, "algorithm.nim");
	{
		NI TMP150;
		NI LOC3;
		NI LOC4;
		if ((NU)(m) >= (NU)(aLen0)) raiseIndexError();
		TMP150 = addInt(m, ((NI) 1));
		if ((NU)((NI)(TMP150)) >= (NU)(aLen0)) raiseIndexError();
		LOC3 = 0;
		LOC3 = cmp.ClEnv? cmp.ClPrc(a[m], a[(NI)(TMP150)], cmp.ClEnv):((TMP151)(cmp.ClPrc))(a[m], a[(NI)(TMP150)]);
		LOC4 = 0;
		LOC4 = HEX2A_93008(LOC3, order);
		if (!(LOC4 <= ((NI) 0))) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	nimln(129, "algorithm.nim");
	j = lo;
	nimln(131, "algorithm.nim");
	{
		if (!!((j <= m))) goto LA9;
		failedassertimpl_89116(((NimStringDesc*) &TMP152));
	}
	LA9: ;
	nimln(133, "algorithm.nim");
	bb = ((NI) 0);
	{
		nimln(134, "algorithm.nim");
		while (1) {
			NI TMP153;
			NI TMP154;
			if (!(j <= m)) goto LA12;
			nimln(121, "algorithm.nim");
			if ((NU)(bb) >= (NU)(bLen0)) raiseIndexError();
			if ((NU)(j) >= (NU)(aLen0)) raiseIndexError();
			b[bb] = a[j];
			nimln(136, "algorithm.nim");
			TMP153 = addInt(bb, ((NI) 1));
			bb = (NI)(TMP153);
			nimln(137, "algorithm.nim");
			TMP154 = addInt(j, ((NI) 1));
			j = (NI)(TMP154);
		} LA12: ;
	}
	nimln(141, "algorithm.nim");
	i = ((NI) 0);
	nimln(142, "algorithm.nim");
	k = lo;
	{
		nimln(144, "algorithm.nim");
		while (1) {
			NIM_BOOL LOC15;
			NI TMP158;
			LOC15 = 0;
			LOC15 = (k < j);
			if (!(LOC15)) goto LA16;
			LOC15 = (j <= hi);
			LA16: ;
			if (!LOC15) goto LA14;
			nimln(145, "algorithm.nim");
			{
				NI LOC19;
				NI LOC20;
				NI TMP156;
				if ((NU)(i) >= (NU)(bLen0)) raiseIndexError();
				if ((NU)(j) >= (NU)(aLen0)) raiseIndexError();
				LOC19 = 0;
				LOC19 = cmp.ClEnv? cmp.ClPrc(b[i], a[j], cmp.ClEnv):((TMP155)(cmp.ClPrc))(b[i], a[j]);
				LOC20 = 0;
				LOC20 = HEX2A_93008(LOC19, order);
				if (!(LOC20 <= ((NI) 0))) goto LA21;
				nimln(121, "algorithm.nim");
				if ((NU)(k) >= (NU)(aLen0)) raiseIndexError();
				if ((NU)(i) >= (NU)(bLen0)) raiseIndexError();
				a[k] = b[i];
				nimln(147, "algorithm.nim");
				TMP156 = addInt(i, ((NI) 1));
				i = (NI)(TMP156);
			}
			goto LA17;
			LA21: ;
			{
				NI TMP157;
				nimln(121, "algorithm.nim");
				if ((NU)(k) >= (NU)(aLen0)) raiseIndexError();
				if ((NU)(j) >= (NU)(aLen0)) raiseIndexError();
				a[k] = a[j];
				nimln(150, "algorithm.nim");
				TMP157 = addInt(j, ((NI) 1));
				j = (NI)(TMP157);
			}
			LA17: ;
			nimln(151, "algorithm.nim");
			TMP158 = addInt(k, ((NI) 1));
			k = (NI)(TMP158);
		} LA14: ;
	}
	{
		nimln(154, "algorithm.nim");
		while (1) {
			NI TMP159;
			NI TMP160;
			if (!(k < j)) goto LA25;
			nimln(121, "algorithm.nim");
			if ((NU)(k) >= (NU)(aLen0)) raiseIndexError();
			if ((NU)(i) >= (NU)(bLen0)) raiseIndexError();
			a[k] = b[i];
			nimln(156, "algorithm.nim");
			TMP159 = addInt(k, ((NI) 1));
			k = (NI)(TMP159);
			nimln(157, "algorithm.nim");
			TMP160 = addInt(i, ((NI) 1));
			i = (NI)(TMP160);
		} LA25: ;
	}
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, sort_94146)(NI* a, NI aLen0, TY94153 cmp, NU8 order) {
	NI n;
	TY94089* b;
	NI TMP147;
	NI s;
	nimfr("sort", "algorithm.nim")
	nimln(190, "algorithm.nim");
	n = aLen0;
	b = 0;
	nimln(192, "algorithm.nim");
	TMP147 = divInt(n, ((NI) 2));
	b = (TY94089*) newSeq((&NTI94089), ((NI)chckRange((NI)(TMP147), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(193, "algorithm.nim");
	s = ((NI) 1);
	{
		nimln(194, "algorithm.nim");
		while (1) {
			NI m;
			NI TMP148;
			NI TMP149;
			NI TMP166;
			if (!(s < n)) goto LA2;
			nimln(195, "algorithm.nim");
			TMP148 = subInt(n, ((NI) 1));
			TMP149 = subInt((NI)(TMP148), s);
			m = (NI)(TMP149);
			{
				nimln(196, "algorithm.nim");
				while (1) {
					NI TMP161;
					NI TMP162;
					NI TMP163;
					NI TMP164;
					NI TMP165;
					nimln(353, "system.nim");
					if (!(((NI) 0) <= m)) goto LA4;
					nimln(197, "algorithm.nim");
					TMP161 = subInt(m, s);
					TMP162 = addInt((NI)(TMP161), ((NI) 1));
					TMP163 = addInt(m, s);
					merge_94191(a, aLen0, b->data, b->Sup.len, (((NI)(TMP162) >= ((NI) 0)) ? (NI)(TMP162) : ((NI) 0)), m, (NI)(TMP163), cmp, order);
					nimln(198, "algorithm.nim");
					TMP164 = mulInt(s, ((NI) 2));
					TMP165 = subInt(m, (NI)(TMP164));
					m = (NI)(TMP165);
				} LA4: ;
			}
			nimln(199, "algorithm.nim");
			TMP166 = mulInt(s, ((NI) 2));
			s = (NI)(TMP166);
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(NI, lowerbound_95983)(NI* a, NI aLen0, NI key, TY94153 cmp) {
	NI result;
	NI count;
	NI TMP174;
	NI TMP175;
	NI step;
	NI pos;
	nimfr("lowerBound", "algorithm.nim")
	result = 0;
	nimln(102, "algorithm.nim");
	result = ((NI) 0);
	nimln(103, "algorithm.nim");
	TMP174 = subInt((aLen0-1), ((NI) 0));
	TMP175 = addInt((NI)(TMP174), ((NI) 1));
	count = (NI)(TMP175);
	step = 0;
	pos = 0;
	{
		nimln(105, "algorithm.nim");
		while (1) {
			NI TMP176;
			NI TMP177;
			nimln(349, "system.nim");
			if (!!((count == ((NI) 0)))) goto LA2;
			nimln(106, "algorithm.nim");
			TMP176 = divInt(count, ((NI) 2));
			step = (NI)(TMP176);
			nimln(107, "algorithm.nim");
			TMP177 = addInt(result, step);
			pos = (NI)(TMP177);
			nimln(108, "algorithm.nim");
			{
				NI LOC5;
				NI TMP179;
				NI TMP180;
				NI TMP181;
				if ((NU)(pos) >= (NU)(aLen0)) raiseIndexError();
				LOC5 = 0;
				LOC5 = cmp.ClEnv? cmp.ClPrc(a[pos], key, cmp.ClEnv):((TMP178)(cmp.ClPrc))(a[pos], key);
				if (!(LOC5 < ((NI) 0))) goto LA6;
				nimln(109, "algorithm.nim");
				TMP179 = addInt(pos, ((NI) 1));
				result = (NI)(TMP179);
				nimln(110, "algorithm.nim");
				TMP180 = addInt(step, ((NI) 1));
				TMP181 = subInt(count, (NI)(TMP180));
				count = (NI)(TMP181);
			}
			goto LA3;
			LA6: ;
			{
				nimln(112, "algorithm.nim");
				count = step;
			}
			LA3: ;
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(NI, lowerbound_95957)(NI* a, NI aLen0, NI key) {
	NI result;
	TY94153 LOC1;
	nimfr("lowerBound", "algorithm.nim")
	result = 0;
	nimln(114, "algorithm.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = ((TMP182) (cmp_94132)); LOC1.ClEnv = NIM_NIL;
	result = lowerbound_95983(a, aLen0, key, LOC1);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void) {
	nimfr("algorithm", "algorithm.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void) {
}

