/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/chaemon/.choosenim/toolchains/nim-0.13.0/lib -o /home/chaemon/git/library-1/nim/other/nimcache/stdlib_sequtils.o /home/chaemon/git/library-1/nim/other/nimcache/stdlib_sequtils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct TY94089 TY94089;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY94089 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, contains_95805)(NI* a, NI aLen0, NI item);
static N_INLINE(NI, find_95815)(NI* a, NI aLen0, NI item);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, failedassertimpl_89116)(NimStringDesc* msg);
STRING_LITERAL(TMP171, "len(a) == L seq modified while iterating over it", 48);
extern TNimType NTI94089; /* seq[int] */
extern TFrame* frameptr_19436;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(NI, find_95815)(NI* a, NI aLen0, NI item) {
	NI result;
	nimfr("find", "system.nim")
{	result = 0;
	{
		NI i_95849;
		NI i_95862;
		i_95849 = 0;
		nimln(1965, "system.nim");
		i_95862 = ((NI) 0);
		{
			nimln(1966, "system.nim");
			while (1) {
				NI TMP168;
				NI TMP169;
				if (!(i_95862 < aLen0)) goto LA3;
				nimln(1967, "system.nim");
				if ((NU)(i_95862) >= (NU)(aLen0)) raiseIndexError();
				i_95849 = a[i_95862];
				nimln(2190, "system.nim");
				{
					if (!(i_95849 == item)) goto LA6;
					goto BeforeRet;
				}
				LA6: ;
				nimln(2191, "system.nim");
				TMP168 = addInt(result, ((NI) 1));
				result = (NI)(TMP168);
				nimln(1968, "system.nim");
				TMP169 = addInt(i_95862, ((NI) 1));
				i_95862 = (NI)(TMP169);
			} LA3: ;
		}
	}
	nimln(2192, "system.nim");
	result = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_95805)(NI* a, NI aLen0, NI item) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("contains", "system.nim")
{	result = 0;
	nimln(2197, "system.nim");
	nimln(352, "system.nim");
	nimln(353, "system.nim");
	nimln(2197, "system.nim");
	LOC1 = 0;
	LOC1 = find_95815(a, aLen0, item);
	result = (((NI) 0) <= LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(TY94089*, deduplicate_95636)(TY94089* seq1) {
	TY94089* result;
	nimfr("deduplicate", "sequtils.nim")
	result = 0;
	nimln(90, "sequtils.nim");
	result = (TY94089*) newSeq((&NTI94089), 0);
	{
		NI itm_95802;
		NI i_95876;
		NI L_95878;
		itm_95802 = 0;
		nimln(3361, "system.nim");
		i_95876 = ((NI) 0);
		nimln(3362, "system.nim");
		L_95878 = (seq1 ? seq1->Sup.len : 0);
		{
			nimln(3363, "system.nim");
			while (1) {
				NI TMP170;
				if (!(i_95876 < L_95878)) goto LA3;
				nimln(3364, "system.nim");
				if ((NU)(i_95876) >= (NU)(seq1->Sup.len)) raiseIndexError();
				itm_95802 = seq1->data[i_95876];
				nimln(92, "sequtils.nim");
				{
					NIM_BOOL LOC6;
					LOC6 = 0;
					LOC6 = contains_95805(result->data, result->Sup.len, itm_95802);
					if (!!(LOC6)) goto LA7;
					result = (TY94089*) incrSeqV2(&(result)->Sup, sizeof(NI));
					result->data[result->Sup.len] = itm_95802;
					++result->Sup.len;
				}
				LA7: ;
				nimln(3365, "system.nim");
				TMP170 = addInt(i_95876, ((NI) 1));
				i_95876 = (NI)(TMP170);
				nimln(3366, "system.nim");
				{
					if (!!(((seq1 ? seq1->Sup.len : 0) == L_95878))) goto LA11;
					failedassertimpl_89116(((NimStringDesc*) &TMP171));
				}
				LA11: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void) {
	nimfr("sequtils", "sequtils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void) {
}

