/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/chaemon/.choosenim/toolchains/nim-0.13.0/lib -o /home/chaemon/git/library-1/nim/tree/verify/nimcache/aoj_grl_5_c_test.o /home/chaemon/git/library-1/nim/tree/verify/nimcache/aoj_grl_5_c_test.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
typedef struct Graph159308 Graph159308;
typedef struct TY159309 TY159309;
typedef struct Edge159312 Edge159312;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47505 Cell47505;
typedef struct Cellseq47521 Cellseq47521;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Cellset47517 Cellset47517;
typedef struct Pagedesc47513 Pagedesc47513;
typedef struct Memregion29688 Memregion29688;
typedef struct Smallchunk29640 Smallchunk29640;
typedef struct Llchunk29682 Llchunk29682;
typedef struct Bigchunk29642 Bigchunk29642;
typedef struct Intset29614 Intset29614;
typedef struct Trunk29610 Trunk29610;
typedef struct Avlnode29686 Avlnode29686;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Slice88082 Slice88082;
typedef struct Doublinglowestcommonancestor159200 Doublinglowestcommonancestor159200;
typedef struct TY159202 TY159202;
typedef struct TY159204 TY159204;
typedef struct TY159873 TY159873;
typedef struct TY159979 TY159979;
typedef struct NimStringDesc NimStringDesc;
typedef struct Basechunk29638 Basechunk29638;
typedef struct Freecell29630 Freecell29630;
struct  Edge159312  {
NI src;
NI dst;
NI weight;
NI rev;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47505  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47521  {
NI len;
NI cap;
Cell47505** d;
};
struct  Cellset47517  {
NI counter;
NI max;
Pagedesc47513* head;
Pagedesc47513** data;
};
typedef Smallchunk29640* TY29703[512];
typedef Trunk29610* Trunkbuckets29612[256];
struct  Intset29614  {
Trunkbuckets29612 data;
};
struct  Memregion29688  {
NI minlargeobj;
NI maxlargeobj;
TY29703 freesmallchunks;
Llchunk29682* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29642* freechunkslist;
Intset29614 chunkstarts;
Avlnode29686* root;
Avlnode29686* deleted;
Avlnode29686* last;
Avlnode29686* freeavlnodes;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47521 zct;
Cellseq47521 decstack;
Cellset47517 cycleroots;
Cellseq47521 tempstack;
NI recgclock;
Memregion29688 region;
Gcstat49814 stat;
};
struct  Slice88082  {
NI a;
NI b;
};
struct  Doublinglowestcommonancestor159200  {
NI Log;
TY159202* dep;
TY159204* table;
};
struct  TY159873  {
NI HEX3Astate;
TY159204* table159739;
TY159202* dep159625;
Graph159308* g159543;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NI idx, NI par, NI d, void* ClEnv);
void* ClEnv;
} TY159741;
typedef N_CLOSURE_PTR(void, TMP47) (NI idx, NI par, NI d);
typedef N_CLOSURE_PTR(void, TMP48) (NI idx, NI par, NI d);
struct TY159979 {
NI Field0;
NI Field1;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY29619[8];
struct  Pagedesc47513  {
Pagedesc47513* next;
NI key;
TY29619 bits;
};
struct  Basechunk29638  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29640  {
  Basechunk29638 Sup;
Smallchunk29640* next;
Smallchunk29640* prev;
Freecell29630* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29682  {
NI size;
NI acc;
Llchunk29682* next;
};
struct  Bigchunk29642  {
  Basechunk29638 Sup;
Bigchunk29642* next;
Bigchunk29642* prev;
NI align;
NF data;
};
struct  Trunk29610  {
Trunk29610* next;
NI key;
TY29619 bits;
};
typedef Avlnode29686* TY29693[2];
struct  Avlnode29686  {
TY29693 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell29630  {
Freecell29630* next;
NI zerofield;
};
struct TY159309 {
  TGenericSeq Sup;
  Edge159312 data[SEQ_DECL_SIZE];
};
struct Graph159308 {
  TGenericSeq Sup;
  TY159309* data[SEQ_DECL_SIZE];
};
struct TY159202 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct TY159204 {
  TGenericSeq Sup;
  TY159202* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, main_159297)(void);
N_NIMCALL(NI, nextint_159016)(NI base);
N_NIMCALL(Graph159308*, newgraph_159301)(NI n);
N_NIMCALL(Graph159308*, newseq_159347)(NI len);
N_NIMCALL(void, TMP36)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP37)(void* p, NI op);
N_NIMCALL(TY159309*, newseq_159329)(NI len);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell47505*, usrtocell_51440)(void* usr);
static N_INLINE(void, rtladdzct_53001)(Cell47505* c);
N_NOINLINE(void, addzct_51417)(Cellseq47521* s, Cell47505* c);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_84004, TNimType* mt);
static N_INLINE(Slice88082, HEX2EHEX2E_102424)(NI a, NI b);
N_NIMCALL(void, addbiedge_159455)(Graph159308** g, NI src, NI dst, NI weight);
N_NIMCALL(Edge159312, newedge_159477)(NI src, NI dst, NI weight, NI rev);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, newdoublinglowestcommonancestor_159538)(Graph159308* g, NI r, Doublinglowestcommonancestor159200* Result);
N_NIMCALL(void, TMP44)(void* p, NI op);
N_NIMCALL(void, TMP45)(void* p, NI op);
N_NIMCALL(void, TMP46)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, HEX2AHEX3D_159560)(NI* x, NI y);
N_NIMCALL(TY159202*, newseq_159591)(NI len);
N_NIMCALL(TY159204*, newseq_159668)(NI len);
N_CLOSURE(void, dfs_159740)(NI idx, NI par, NI d, void* ClEnv);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NI, query_159968)(Doublinglowestcommonancestor159200* self, NI u_159975, NI v_159977);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, aoj_grl_5_c_testInit000)(void);
NIM_EXTERNC N_NOINLINE(void, aoj_grl_5_c_testDatInit000)(void);
TNimType NTI159312; /* Edge */
extern TNimType NTI104; /* int */
TNimType NTI159309; /* seq[Edge[system.int]] */
TNimType NTI159308; /* Graph */
extern Gcheap49818 gch_49859;
TNimType NTI159873; /* object */
TNimType NTI159875; /* range -1..0(int) */
TNimType NTI159202; /* seq[int] */
TNimType NTI159204; /* seq[seq[int]] */
TNimType NTI159872; /* ref object */

N_NIMCALL(NI, nextint_159016)(NI base) {
	NI result;
	result = 0;
	scanf("%lld", (&result));
	result -= base;
	return result;
}
N_NIMCALL(void, TMP36)(void* p, NI op) {
	TY159309* a;
	NI LOC1;
	a = (TY159309*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}
N_NIMCALL(void, TMP37)(void* p, NI op) {
	Graph159308* a;
	NI LOC1;
	a = (Graph159308*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(Cell47505*, usrtocell_51440)(void* usr) {
	Cell47505* result;
	result = 0;
	result = ((Cell47505*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47505))))));
	return result;
}

static N_INLINE(void, rtladdzct_53001)(Cell47505* c) {
	addzct_51417((&gch_49859.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		Cell47505* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_51440(src);
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell47505* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_51440((*dest));
		{
			(*c).refcount -= ((NI) 8);
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			rtladdzct_53001(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(Graph159308*, newgraph_159301)(NI n) {
	Graph159308* result_159321;
	Graph159308* result_159323;
{	result_159321 = 0;
	result_159323 = newseq_159347(((NI) (n)));
	{
		NI i_159325;
		NI HEX3Atmp_159392;
		NI res_159395;
		i_159325 = 0;
		HEX3Atmp_159392 = 0;
		HEX3Atmp_159392 = (n - 1);
		res_159395 = ((NI) 0);
		{
			while (1) {
				if (!(res_159395 <= HEX3Atmp_159392)) goto LA3;
				i_159325 = res_159395;
				asgnRefNoCycle((void**) (&result_159323->data[i_159325]), newseq_159329(((NI) 0)));
				res_159395 += ((NI) 1);
			} LA3: ;
		}
	}
	genericSeqAssign((&result_159321), result_159323, (&NTI159308));
	goto BeforeRet;
	}BeforeRet: ;
	return result_159321;
}

static N_INLINE(Slice88082, HEX2EHEX2E_102424)(NI a, NI b) {
	Slice88082 result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

N_NIMCALL(Edge159312, newedge_159477)(NI src, NI dst, NI weight, NI rev) {
	Edge159312 result;
	Edge159312 e;
{	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&e), 0, sizeof(e));
	e.src = src;
	e.dst = dst;
	e.weight = weight;
	e.rev = rev;
	result = e;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, addbiedge_159455)(Graph159308** g, NI src, NI dst, NI weight) {
	Edge159312 LOC1;
	Edge159312 LOC2;
	LOC1 = newedge_159477(src, dst, weight, ((*g)->data[dst] ? (*g)->data[dst]->Sup.len : 0));
	(*g)->data[src] = (TY159309*) incrSeqV2(&((*g)->data[src])->Sup, sizeof(Edge159312));
	(*g)->data[src]->data[(*g)->data[src]->Sup.len] = LOC1;
	++(*g)->data[src]->Sup.len;
	LOC2 = newedge_159477(dst, src, weight, (NI)(((*g)->data[src] ? (*g)->data[src]->Sup.len : 0) - ((NI) 1)));
	(*g)->data[dst] = (TY159309*) incrSeqV2(&((*g)->data[dst])->Sup, sizeof(Edge159312));
	(*g)->data[dst]->data[(*g)->data[dst]->Sup.len] = LOC2;
	++(*g)->data[dst]->Sup.len;
}
N_NIMCALL(void, TMP44)(void* p, NI op) {
	TY159202* a;
	NI LOC1;
	a = (TY159202*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}
N_NIMCALL(void, TMP45)(void* p, NI op) {
	TY159204* a;
	NI LOC1;
	a = (TY159204*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}
N_NIMCALL(void, TMP46)(void* p, NI op) {
	TY159873* a;
	a = (TY159873*)p;
	nimGCvisit((void*)(*a).table159739, op);
	nimGCvisit((void*)(*a).dep159625, op);
	nimGCvisit((void*)(*a).g159543, op);
}

static N_INLINE(void, HEX2AHEX3D_159560)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

N_CLOSURE(void, dfs_159740)(NI idx, NI par, NI d, void* ClEnv) {
	TY159873* HEX3Aenvp_159876;
	HEX3Aenvp_159876 = (TY159873*) ClEnv;
	(*HEX3Aenvp_159876).table159739->data[((NI) 0)]->data[idx] = par;
	(*HEX3Aenvp_159876).dep159625->data[idx] = d;
	{
		Edge159312 e_159802;
		TY159309* HEX3Atmp_159804;
		NI i_159807;
		NI L_159809;
		memset((void*)(&e_159802), 0, sizeof(e_159802));
		HEX3Atmp_159804 = 0;
		HEX3Atmp_159804 = (*HEX3Aenvp_159876).g159543->data[idx];
		i_159807 = ((NI) 0);
		L_159809 = (HEX3Atmp_159804 ? HEX3Atmp_159804->Sup.len : 0);
		{
			while (1) {
				if (!(i_159807 < L_159809)) goto LA3;
				e_159802 = HEX3Atmp_159804->data[i_159807];
				{
					TY159741 LOC8;
					if (!!((e_159802.dst == par))) goto LA6;
					memset((void*)(&LOC8), 0, sizeof(LOC8));
					LOC8.ClPrc = dfs_159740; LOC8.ClEnv = HEX3Aenvp_159876;
					LOC8.ClEnv? LOC8.ClPrc(e_159802.dst, idx, (NI)(d + ((NI) 1)), LOC8.ClEnv):((TMP47)(LOC8.ClPrc))(e_159802.dst, idx, (NI)(d + ((NI) 1)));
				}
				LA6: ;
				i_159807 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_NIMCALL(void, newdoublinglowestcommonancestor_159538)(Graph159308* g, NI r, Doublinglowestcommonancestor159200* Result) {
	TY159873* HEX3Aenv_159880;
	NI Log;
	NI t;
	TY159202* result_159587;
	TY159204* result_159627;
	TY159741 LOC12;
	Doublinglowestcommonancestor159200 LOC26;
{	HEX3Aenv_159880 = 0;
	HEX3Aenv_159880 = (TY159873*) newObj((&NTI159872), sizeof(TY159873));
	genericSeqAssign((&(*HEX3Aenv_159880).g159543), g, (&NTI159308));
	Log = ((NI) 0);
	t = ((NI) 1);
	{
		while (1) {
			if (!(t <= ((*HEX3Aenv_159880).g159543 ? (*HEX3Aenv_159880).g159543->Sup.len : 0))) goto LA2;
			HEX2AHEX3D_159560((&t), ((NI) 2));
			Log += ((NI) 1);
		} LA2: ;
	}
	result_159587 = newseq_159591(((NI) (((*HEX3Aenv_159880).g159543 ? (*HEX3Aenv_159880).g159543->Sup.len : 0))));
	{
		NI i_159589;
		NI HEX3Atmp_159883;
		NI res_159886;
		i_159589 = 0;
		HEX3Atmp_159883 = 0;
		HEX3Atmp_159883 = (((*HEX3Aenv_159880).g159543 ? (*HEX3Aenv_159880).g159543->Sup.len : 0) - 1);
		res_159886 = ((NI) 0);
		{
			while (1) {
				if (!(res_159886 <= HEX3Atmp_159883)) goto LA5;
				i_159589 = res_159886;
				result_159587->data[i_159589] = ((NI) 0);
				res_159886 += ((NI) 1);
			} LA5: ;
		}
	}
	genericSeqAssign((&(*HEX3Aenv_159880).dep159625), result_159587, (&NTI159202));
	result_159627 = newseq_159668(((NI) (Log)));
	{
		NI i_159629;
		NI HEX3Atmp_159899;
		NI res_159902;
		i_159629 = 0;
		HEX3Atmp_159899 = 0;
		HEX3Atmp_159899 = (Log - 1);
		res_159902 = ((NI) 0);
		{
			while (1) {
				TY159202* result_159711;
				if (!(res_159902 <= HEX3Atmp_159899)) goto LA8;
				i_159629 = res_159902;
				result_159711 = newseq_159591(((NI) (((*HEX3Aenv_159880).g159543 ? (*HEX3Aenv_159880).g159543->Sup.len : 0))));
				{
					NI i_159713;
					NI HEX3Atmp_159892;
					NI res_159895;
					i_159713 = 0;
					HEX3Atmp_159892 = 0;
					HEX3Atmp_159892 = (((*HEX3Aenv_159880).g159543 ? (*HEX3Aenv_159880).g159543->Sup.len : 0) - 1);
					res_159895 = ((NI) 0);
					{
						while (1) {
							if (!(res_159895 <= HEX3Atmp_159892)) goto LA11;
							i_159713 = res_159895;
							result_159711->data[i_159713] = ((NI) -1);
							res_159895 += ((NI) 1);
						} LA11: ;
					}
				}
				genericSeqAssign((&result_159627->data[i_159629]), result_159711, (&NTI159202));
				res_159902 += ((NI) 1);
			} LA8: ;
		}
	}
	genericSeqAssign((&(*HEX3Aenv_159880).table159739), result_159627, (&NTI159204));
	memset((void*)(&LOC12), 0, sizeof(LOC12));
	LOC12.ClPrc = dfs_159740; LOC12.ClEnv = HEX3Aenv_159880;
	LOC12.ClEnv? LOC12.ClPrc(r, ((NI) -1), ((NI) 0), LOC12.ClEnv):((TMP48)(LOC12.ClPrc))(r, ((NI) -1), ((NI) 0));
	{
		NI k_159835;
		Slice88082 HEX3Atmp_159922;
		k_159835 = 0;
		memset((void*)(&HEX3Atmp_159922), 0, sizeof(HEX3Atmp_159922));
		HEX3Atmp_159922 = HEX2EHEX2E_102424(((NI) 0), ((NI)(Log - ((NI) 1)) - 1));
		{
			NI x_159926;
			NI HEX3Atmp_159928;
			NI HEX3Atmp_159930;
			NI res_159932;
			x_159926 = 0;
			HEX3Atmp_159928 = 0;
			HEX3Atmp_159930 = 0;
			HEX3Atmp_159928 = HEX3Atmp_159922.a;
			HEX3Atmp_159930 = HEX3Atmp_159922.b;
			res_159932 = HEX3Atmp_159928;
			{
				while (1) {
					if (!(res_159932 <= HEX3Atmp_159930)) goto LA16;
					x_159926 = res_159932;
					k_159835 = x_159926;
					{
						NI i_159869;
						Slice88082 HEX3Atmp_159908;
						i_159869 = 0;
						memset((void*)(&HEX3Atmp_159908), 0, sizeof(HEX3Atmp_159908));
						HEX3Atmp_159908 = HEX2EHEX2E_102424(((NI) 0), (((*HEX3Aenv_159880).table159739->data[k_159835] ? (*HEX3Aenv_159880).table159739->data[k_159835]->Sup.len : 0) - 1));
						{
							NI x_159912;
							NI HEX3Atmp_159914;
							NI HEX3Atmp_159916;
							NI res_159918;
							x_159912 = 0;
							HEX3Atmp_159914 = 0;
							HEX3Atmp_159916 = 0;
							HEX3Atmp_159914 = HEX3Atmp_159908.a;
							HEX3Atmp_159916 = HEX3Atmp_159908.b;
							res_159918 = HEX3Atmp_159914;
							{
								while (1) {
									if (!(res_159918 <= HEX3Atmp_159916)) goto LA20;
									x_159912 = res_159918;
									i_159869 = x_159912;
									{
										if (!((*HEX3Aenv_159880).table159739->data[k_159835]->data[i_159869] == ((NI) -1))) goto LA23;
										(*HEX3Aenv_159880).table159739->data[(NI)(k_159835 + ((NI) 1))]->data[i_159869] = ((NI) -1);
									}
									goto LA21;
									LA23: ;
									{
										(*HEX3Aenv_159880).table159739->data[(NI)(k_159835 + ((NI) 1))]->data[i_159869] = (*HEX3Aenv_159880).table159739->data[k_159835]->data[(*HEX3Aenv_159880).table159739->data[k_159835]->data[i_159869]];
									}
									LA21: ;
									res_159918 += ((NI) 1);
								} LA20: ;
							}
						}
					}
					res_159932 += ((NI) 1);
				} LA16: ;
			}
		}
	}
	memset((void*)(&LOC26), 0, sizeof(LOC26));
	memset((void*)(&LOC26), 0, sizeof(LOC26));
	LOC26.Log = Log;
	genericSeqAssign((&LOC26.dep), (*HEX3Aenv_159880).dep159625, (&NTI159202));
	genericSeqAssign((&LOC26.table), (*HEX3Aenv_159880).table159739, (&NTI159204));
	(*Result).Log = LOC26.Log;
	unsureAsgnRef((void**) (&(*Result).dep), LOC26.dep);
	unsureAsgnRef((void**) (&(*Result).table), LOC26.table);
	goto BeforeRet;
	}BeforeRet: ;
}

N_NIMCALL(NI, query_159968)(Doublinglowestcommonancestor159200* self, NI u_159975, NI v_159977) {
	NI result;
	TY159979 LOC1;
	NI u;
	NI v;
{	result = 0;
	LOC1.Field0 = u_159975;
	LOC1.Field1 = v_159977;
	u = LOC1.Field0;
	v = LOC1.Field1;
	{
		NI LOC6;
		if (!((*self).dep->data[v] < (*self).dep->data[u])) goto LA4;
		LOC6 = 0;
		LOC6 = u;
		u = v;
		v = LOC6;
	}
	LA4: ;
	{
		NI i_160002;
		NI HEX3Atmp_160016;
		NI res_160019;
		i_160002 = 0;
		HEX3Atmp_160016 = 0;
		HEX3Atmp_160016 = (NI)((*self).Log - ((NI) 1));
		res_160019 = HEX3Atmp_160016;
		{
			while (1) {
				if (!(((NI) 0) <= res_160019)) goto LA9;
				i_160002 = res_160019;
				{
					if (!(((NI) 0) < ((NI) ((NI)((NI)((NU64)((NI)((*self).dep->data[v] - (*self).dep->data[u])) >> (NU64)(i_160002)) & ((NI) 1)))))) goto LA12;
					v = (*self).table->data[i_160002]->data[v];
				}
				LA12: ;
				res_160019 -= ((NI) 1);
			} LA9: ;
		}
	}
	{
		if (!(u == v)) goto LA16;
		result = u;
		goto BeforeRet;
	}
	LA16: ;
	{
		NI i_160014;
		NI HEX3Atmp_160024;
		NI res_160027;
		i_160014 = 0;
		HEX3Atmp_160024 = 0;
		HEX3Atmp_160024 = (NI)((*self).Log - ((NI) 1));
		res_160027 = HEX3Atmp_160024;
		{
			while (1) {
				if (!(((NI) 0) <= res_160027)) goto LA20;
				i_160014 = res_160027;
				{
					if (!!(((*self).table->data[i_160014]->data[u] == (*self).table->data[i_160014]->data[v]))) goto LA23;
					u = (*self).table->data[i_160014]->data[u];
					v = (*self).table->data[i_160014]->data[v];
				}
				LA23: ;
				res_160027 -= ((NI) 1);
			} LA20: ;
		}
	}
	result = (*self).table->data[((NI) 0)]->data[u];
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, main_159297)(void) {
	NI N;
	Graph159308* g;
	Doublinglowestcommonancestor159200 lca;
	NI Q;
	N = nextint_159016(((NI) 0));
	g = newgraph_159301(N);
	{
		NI i_159425;
		Slice88082 HEX3Atmp_160049;
		i_159425 = 0;
		memset((void*)(&HEX3Atmp_160049), 0, sizeof(HEX3Atmp_160049));
		HEX3Atmp_160049 = HEX2EHEX2E_102424(((NI) 0), (N - 1));
		{
			NI x_160053;
			NI HEX3Atmp_160055;
			NI HEX3Atmp_160057;
			NI res_160059;
			x_160053 = 0;
			HEX3Atmp_160055 = 0;
			HEX3Atmp_160057 = 0;
			HEX3Atmp_160055 = HEX3Atmp_160049.a;
			HEX3Atmp_160057 = HEX3Atmp_160049.b;
			res_160059 = HEX3Atmp_160055;
			{
				while (1) {
					NI k;
					if (!(res_160059 <= HEX3Atmp_160057)) goto LA4;
					x_160053 = res_160059;
					i_159425 = x_160053;
					k = nextint_159016(((NI) 0));
					{
						NI j_159452;
						Slice88082 HEX3Atmp_160035;
						j_159452 = 0;
						memset((void*)(&HEX3Atmp_160035), 0, sizeof(HEX3Atmp_160035));
						HEX3Atmp_160035 = HEX2EHEX2E_102424(((NI) 0), (k - 1));
						{
							NI x_160039;
							NI HEX3Atmp_160041;
							NI HEX3Atmp_160043;
							NI res_160045;
							x_160039 = 0;
							HEX3Atmp_160041 = 0;
							HEX3Atmp_160043 = 0;
							HEX3Atmp_160041 = HEX3Atmp_160035.a;
							HEX3Atmp_160043 = HEX3Atmp_160035.b;
							res_160045 = HEX3Atmp_160041;
							{
								while (1) {
									NI c;
									if (!(res_160045 <= HEX3Atmp_160043)) goto LA8;
									x_160039 = res_160045;
									j_159452 = x_160039;
									c = nextint_159016(((NI) 0));
									addbiedge_159455((&g), i_159425, c, ((NI) 1));
									res_160045 += ((NI) 1);
								} LA8: ;
							}
						}
					}
					res_160059 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	memset((void*)(&lca), 0, sizeof(lca));
	memset((void*)(&lca), 0, sizeof(lca));
	newdoublinglowestcommonancestor_159538(g, ((NI) 0), (&lca));
	Q = nextint_159016(((NI) 0));
	{
		NI i_159964;
		Slice88082 HEX3Atmp_160064;
		i_159964 = 0;
		memset((void*)(&HEX3Atmp_160064), 0, sizeof(HEX3Atmp_160064));
		HEX3Atmp_160064 = HEX2EHEX2E_102424(((NI) 0), (Q - 1));
		{
			NI x_160068;
			NI HEX3Atmp_160070;
			NI HEX3Atmp_160072;
			NI res_160074;
			x_160068 = 0;
			HEX3Atmp_160070 = 0;
			HEX3Atmp_160072 = 0;
			HEX3Atmp_160070 = HEX3Atmp_160064.a;
			HEX3Atmp_160072 = HEX3Atmp_160064.b;
			res_160074 = HEX3Atmp_160070;
			{
				while (1) {
					NI x;
					NI y;
					NI LOC13;
					NimStringDesc* LOC14;
					if (!(res_160074 <= HEX3Atmp_160072)) goto LA12;
					x_160068 = res_160074;
					i_159964 = x_160068;
					x = nextint_159016(((NI) 0));
					y = nextint_159016(((NI) 0));
					LOC13 = 0;
					LOC13 = query_159968((&lca), x, y);
					LOC14 = 0;
					LOC14 = nimIntToStr(LOC13);
					printf("%s\012", LOC14? (LOC14)->data:"nil");
					fflush(stdout);
					res_160074 += ((NI) 1);
				} LA12: ;
			}
		}
	}
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_algorithmDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_timesDatInit000();
	stdlib_mathDatInit000();
	stdlib_tablesDatInit000();
	stdlib_macrosDatInit000();
	stdlib_posixDatInit000();
	stdlib_osDatInit000();
	stdlib_setsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_futureDatInit000();
	aoj_grl_5_c_testDatInit000();
	stdlib_algorithmInit000();
	stdlib_sequtilsInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_timesInit000();
	stdlib_mathInit000();
	stdlib_tablesInit000();
	stdlib_macrosInit000();
	stdlib_posixInit000();
	stdlib_osInit000();
	stdlib_setsInit000();
	stdlib_streamsInit000();
	stdlib_futureInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	aoj_grl_5_c_testInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, aoj_grl_5_c_testInit000)(void) {
	main_159297();
}

NIM_EXTERNC N_NOINLINE(void, aoj_grl_5_c_testDatInit000)(void) {
static TNimNode* TMP35[4];
static TNimNode* TMP43[4];
static TNimNode TMP3[10];
NTI159312.size = sizeof(Edge159312);
NTI159312.kind = 18;
NTI159312.base = 0;
NTI159312.flags = 3;
TMP35[0] = &TMP3[1];
TMP3[1].kind = 1;
TMP3[1].offset = offsetof(Edge159312, src);
TMP3[1].typ = (&NTI104);
TMP3[1].name = "src";
TMP35[1] = &TMP3[2];
TMP3[2].kind = 1;
TMP3[2].offset = offsetof(Edge159312, dst);
TMP3[2].typ = (&NTI104);
TMP3[2].name = "dst";
TMP35[2] = &TMP3[3];
TMP3[3].kind = 1;
TMP3[3].offset = offsetof(Edge159312, weight);
TMP3[3].typ = (&NTI104);
TMP3[3].name = "weight";
TMP35[3] = &TMP3[4];
TMP3[4].kind = 1;
TMP3[4].offset = offsetof(Edge159312, rev);
TMP3[4].typ = (&NTI104);
TMP3[4].name = "rev";
TMP3[0].len = 4; TMP3[0].kind = 2; TMP3[0].sons = &TMP35[0];
NTI159312.node = &TMP3[0];
NTI159309.size = sizeof(TY159309*);
NTI159309.kind = 24;
NTI159309.base = (&NTI159312);
NTI159309.flags = 2;
NTI159309.marker = TMP36;
NTI159308.size = sizeof(Graph159308*);
NTI159308.kind = 24;
NTI159308.base = (&NTI159309);
NTI159308.flags = 2;
NTI159308.marker = TMP37;
NTI159873.size = sizeof(TY159873);
NTI159873.kind = 18;
NTI159873.base = 0;
NTI159873.flags = 2;
TMP43[0] = &TMP3[6];
NTI159875.size = sizeof(NI);
NTI159875.kind = 20;
NTI159875.base = (&NTI104);
NTI159875.flags = 3;
TMP3[6].kind = 1;
TMP3[6].offset = offsetof(TY159873, HEX3Astate);
TMP3[6].typ = (&NTI159875);
TMP3[6].name = ":state";
TMP43[1] = &TMP3[7];
NTI159202.size = sizeof(TY159202*);
NTI159202.kind = 24;
NTI159202.base = (&NTI104);
NTI159202.flags = 2;
NTI159202.marker = TMP44;
NTI159204.size = sizeof(TY159204*);
NTI159204.kind = 24;
NTI159204.base = (&NTI159202);
NTI159204.flags = 2;
NTI159204.marker = TMP45;
TMP3[7].kind = 1;
TMP3[7].offset = offsetof(TY159873, table159739);
TMP3[7].typ = (&NTI159204);
TMP3[7].name = "table159739";
TMP43[2] = &TMP3[8];
TMP3[8].kind = 1;
TMP3[8].offset = offsetof(TY159873, dep159625);
TMP3[8].typ = (&NTI159202);
TMP3[8].name = "dep159625";
TMP43[3] = &TMP3[9];
TMP3[9].kind = 1;
TMP3[9].offset = offsetof(TY159873, g159543);
TMP3[9].typ = (&NTI159308);
TMP3[9].name = "g159543";
TMP3[5].len = 4; TMP3[5].kind = 2; TMP3[5].sons = &TMP43[0];
NTI159873.node = &TMP3[5];
NTI159872.size = sizeof(TY159873*);
NTI159872.kind = 22;
NTI159872.base = (&NTI159873);
NTI159872.flags = 2;
NTI159872.marker = TMP46;
}

