/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   g++ -c  -w -w -fpermissive -O3 -fno-strict-aliasing  -I/home/chaemon/.choosenim/toolchains/nim-0.13.0/lib -o /home/chaemon/git/library-1/nim/tree/verify/nimcache/aoj_grl_5_c_2_test.o /home/chaemon/git/library-1/nim/tree/verify/nimcache/aoj_grl_5_c_2_test.cpp */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
struct Graph159415;
struct TY159416;
struct Edge159419;
struct TGenericSeq;
struct TNimType;
struct TNimNode;
struct Cell47306;
struct Cellseq47322;
struct Gcheap49618;
struct Gcstack49616;
struct Cellset47318;
struct Pagedesc47314;
struct Memregion29488;
struct Smallchunk29440;
struct Llchunk29482;
struct Bigchunk29442;
struct Intset29414;
struct Trunk29410;
struct Avlnode29486;
struct Gcstat49614;
struct Slice87882;
struct Heavylightdecomposition159200;
struct TY159201;
struct TY160017;
struct TY160073;
struct NimStringDesc;
struct Basechunk29438;
struct Freecell29430;
struct  Edge159419  {
NI src;
NI dst;
NI weight;
NI rev;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47306  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47322  {
NI len;
NI cap;
Cell47306** d;
};
struct  Cellset47318  {
NI counter;
NI max;
Pagedesc47314* head;
Pagedesc47314** data;
};
typedef Smallchunk29440* TY29503[512];
typedef Trunk29410* Trunkbuckets29412[256];
struct  Intset29414  {
Trunkbuckets29412 data;
};
struct  Memregion29488  {
NI minlargeobj;
NI maxlargeobj;
TY29503 freesmallchunks;
Llchunk29482* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29442* freechunkslist;
Intset29414 chunkstarts;
Avlnode29486* root;
Avlnode29486* deleted;
Avlnode29486* last;
Avlnode29486* freeavlnodes;
};
struct  Gcstat49614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap49618  {
Gcstack49616* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47322 zct;
Cellseq47322 decstack;
Cellset47318 cycleroots;
Cellseq47322 tempstack;
NI recgclock;
Memregion29488 region;
Gcstat49614 stat;
};
struct  Slice87882  {
NI a;
NI b;
};
struct  Heavylightdecomposition159200  {
TY159201* sz;
TY159201* ina;
TY159201* outa;
TY159201* head;
TY159201* rev;
TY159201* par;
};
struct  TY160017  {
NI HEX3Astate;
TY159201* par159686;
TY159201* sz159681;
Graph159415* g159654;
TY159201* ina159682;
TY159201* rev159685;
TY159201* head159684;
TY159201* outa159683;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NI idx, NI p, void* ClEnv);
void* ClEnv;
} TY159688;
typedef N_CLOSURE_PTR(void, TMP45) (NI idx, NI p);
typedef N_CLOSURE_PTR(void, TMP46) (NI idx, NI p);
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NI idx, NI par, NI& times, void* ClEnv);
void* ClEnv;
} TY159831;
typedef N_CLOSURE_PTR(void, TMP47) (NI idx, NI par, NI& times);
typedef N_CLOSURE_PTR(void, TMP48) (NI idx, NI par, NI& times);
struct TY160073 {
NI Field0;
NI Field1;
};
struct  NimStringDesc  : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Gcstack49616  {
Gcstack49616* prev;
Gcstack49616* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY29419[8];
struct  Pagedesc47314  {
Pagedesc47314* next;
NI key;
TY29419 bits;
};
struct  Basechunk29438  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29440  : public Basechunk29438 {
Smallchunk29440* next;
Smallchunk29440* prev;
Freecell29430* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29482  {
NI size;
NI acc;
Llchunk29482* next;
};
struct  Bigchunk29442  : public Basechunk29438 {
Bigchunk29442* next;
Bigchunk29442* prev;
NI align;
NF data;
};
struct  Trunk29410  {
Trunk29410* next;
NI key;
TY29419 bits;
};
typedef Avlnode29486* TY29493[2];
struct  Avlnode29486  {
TY29493 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell29430  {
Freecell29430* next;
NI zerofield;
};
struct TY159416 : TGenericSeq {
  Edge159419 data[SEQ_DECL_SIZE];
};
struct Graph159415 : TGenericSeq {
  TY159416* data[SEQ_DECL_SIZE];
};
struct TY159201 : TGenericSeq {
  NI data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, main_159404)(void);
N_NIMCALL(NI, nextint_159016)(NI base);
N_NIMCALL(Graph159415*, newgraph_159408)(NI n);
N_NIMCALL(Graph159415*, newseq_159454)(NI len);
N_NIMCALL(void, TMP36)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP37)(void* p, NI op);
N_NIMCALL(TY159416*, newseq_159436)(NI len);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell47306*, usrtocell_51241)(void* usr);
static N_INLINE(void, rtladdzct_52801)(Cell47306* c);
N_NOINLINE(void, addzct_51217)(Cellseq47322& s, Cell47306* c);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_83804, TNimType* mt);
static N_INLINE(Slice87882, HEX2EHEX2E_102424)(NI a, NI b);
N_NIMCALL(void, addbiedge_159562)(Graph159415*& g, NI src, NI dst, NI weight);
N_NIMCALL(Edge159419, newedge_159584)(NI src, NI dst, NI weight, NI rev);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, newheavylightdecomposition_159645)(Graph159415* g_159650, Heavylightdecomposition159200* Result);
N_NIMCALL(void, TMP43)(void* p, NI op);
N_NIMCALL(void, TMP44)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(TY159201*, newseq_159664)(NI len);
N_CLOSURE(void, dfssz_159687)(NI idx, NI p, void* ClEnv);
N_CLOSURE(void, dfshld_159830)(NI idx, NI par, NI& times, void* ClEnv);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(NI, lca_160062)(Heavylightdecomposition159200* self, NI u_160069, NI v_160071);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, aoj_grl_5_c_2_testInit000)(void);
NIM_EXTERNC N_NOINLINE(void, aoj_grl_5_c_2_testDatInit000)(void);
TNimType NTI159419; /* Edge */
extern TNimType NTI104; /* int */
TNimType NTI159416; /* seq[Edge[system.int]] */
TNimType NTI159415; /* Graph */
extern Gcheap49618 gch_49659;
TNimType NTI160017; /* object */
TNimType NTI160019; /* range -1..0(int) */
TNimType NTI159201; /* seq[int] */
TNimType NTI160016; /* ref object */
TNimType NTI159200; /* HeavyLightDecomposition */

N_NIMCALL(NI, nextint_159016)(NI base) {
	NI result;
	result = 0;
	scanf("%lld", (&result));
	result -= base;
	return result;
}
N_NIMCALL(void, TMP36)(void* p, NI op) {
	TY159416* a;
	NI LOC1;
	a = (TY159416*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->len; LOC1++) {
	}
}
N_NIMCALL(void, TMP37)(void* p, NI op) {
	Graph159415* a;
	NI LOC1;
	a = (Graph159415*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(Cell47306*, usrtocell_51241)(void* usr) {
	Cell47306* result;
	result = 0;
	result = ((Cell47306*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47306))))));
	return result;
}

static N_INLINE(void, rtladdzct_52801)(Cell47306* c) {
	addzct_51217(gch_49659.zct, c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		if (!!((src == NIM_NIL))) goto LA3;
{		Cell47306* c = usrtocell_51241(src);
		(*c).refcount += ((NI) 8);
}	}
	LA3: ;
	{
		if (!!(((*dest) == NIM_NIL))) goto LA7;
{		Cell47306* c = usrtocell_51241((*dest));
		{
			(*c).refcount -= ((NI) 8);
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
{			rtladdzct_52801(c);
}		}
		LA11: ;
}	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(Graph159415*, newgraph_159408)(NI n) {
	Graph159415* result_159428;
	Graph159415* result_159430;
{	result_159428 = 0;
	result_159430 = newseq_159454(((NI) (n)));
	{
		NI i_159432;
		NI HEX3Atmp_159499;
		i_159432 = 0;
		HEX3Atmp_159499 = 0;
		HEX3Atmp_159499 = (n - 1);
		NI res_159502 = ((NI) 0);
		{
			while (1) {
				if (!(res_159502 <= HEX3Atmp_159499)) goto LA3;
				i_159432 = res_159502;
				asgnRefNoCycle((void**) (&result_159430->data[i_159432]), newseq_159436(((NI) 0)));
				res_159502 += ((NI) 1);
			} LA3: ;
		}
	}
	genericSeqAssign((&result_159428), result_159430, (&NTI159415));
	goto BeforeRet;
	}BeforeRet: ;
	return result_159428;
}

static N_INLINE(Slice87882, HEX2EHEX2E_102424)(NI a, NI b) {
	Slice87882 result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

N_NIMCALL(Edge159419, newedge_159584)(NI src, NI dst, NI weight, NI rev) {
	Edge159419 result;
	Edge159419 e;
{	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&e), 0, sizeof(e));
	e.src = src;
	e.dst = dst;
	e.weight = weight;
	e.rev = rev;
	result = e;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, addbiedge_159562)(Graph159415*& g, NI src, NI dst, NI weight) {
	Edge159419 LOC1;
	Edge159419 LOC2;
	LOC1 = newedge_159584(src, dst, weight, (g->data[dst] ? g->data[dst]->len : 0));
	g->data[src] = (TY159416*) incrSeqV2(g->data[src], sizeof(Edge159419));
	g->data[src]->data[g->data[src]->len] = LOC1;
	++g->data[src]->len;
	LOC2 = newedge_159584(dst, src, weight, (NI)((g->data[src] ? g->data[src]->len : 0) - ((NI) 1)));
	g->data[dst] = (TY159416*) incrSeqV2(g->data[dst], sizeof(Edge159419));
	g->data[dst]->data[g->data[dst]->len] = LOC2;
	++g->data[dst]->len;
}
N_NIMCALL(void, TMP43)(void* p, NI op) {
	TY159201* a;
	NI LOC1;
	a = (TY159201*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->len; LOC1++) {
	}
}
N_NIMCALL(void, TMP44)(void* p, NI op) {
	TY160017* a;
	a = (TY160017*)p;
	nimGCvisit((void*)(*a).par159686, op);
	nimGCvisit((void*)(*a).sz159681, op);
	nimGCvisit((void*)(*a).g159654, op);
	nimGCvisit((void*)(*a).ina159682, op);
	nimGCvisit((void*)(*a).rev159685, op);
	nimGCvisit((void*)(*a).head159684, op);
	nimGCvisit((void*)(*a).outa159683, op);
}

N_CLOSURE(void, dfssz_159687)(NI idx, NI p, void* ClEnv) {
	TY160017* HEX3Aenvp_160020;
	HEX3Aenvp_160020 = (TY160017*) ClEnv;
	(*HEX3Aenvp_160020).par159686->data[idx] = p;
	(*HEX3Aenvp_160020).sz159681->data[idx] = ((NI) 1);
	{
		NIM_BOOL LOC3;
		NI LOC7;
		LOC3 = 0;
		LOC3 = (((NI) 0) < ((*HEX3Aenvp_160020).g159654->data[idx] ? (*HEX3Aenvp_160020).g159654->data[idx]->len : 0));
		if (!(LOC3)) goto LA4;
		LOC3 = ((*HEX3Aenvp_160020).g159654->data[idx]->data[((NI) 0)].dst == p);
		LA4: ;
		if (!LOC3) goto LA5;
{		LOC7 = 0;
		LOC7 = (*HEX3Aenvp_160020).g159654->data[idx]->data[((NI) 0)].dst;
		(*HEX3Aenvp_160020).g159654->data[idx]->data[((NI) 0)].dst = (*HEX3Aenvp_160020).g159654->data[idx]->data[(NI)(((*HEX3Aenvp_160020).g159654->data[idx] ? (*HEX3Aenvp_160020).g159654->data[idx]->len : 0) - ((NI) 1))].dst;
		(*HEX3Aenvp_160020).g159654->data[idx]->data[(NI)(((*HEX3Aenvp_160020).g159654->data[idx] ? (*HEX3Aenvp_160020).g159654->data[idx]->len : 0) - ((NI) 1))].dst = LOC7;
}	}
	LA5: ;
	{
		Edge159419& e_159803;
		e_159803 = 0;
		NI i_159827 = ((NI) 0);
		NI L_159829 = ((&(*HEX3Aenvp_160020).g159654->data[idx]) ? (&(*HEX3Aenvp_160020).g159654->data[idx])->len : 0);
		{
			while (1) {
				if (!(i_159827 < L_159829)) goto LA10;
				e_159803 = (&(&(*HEX3Aenvp_160020).g159654->data[idx])->data[i_159827]);
				{
					TY159688 LOC16;
					{
						if (!(e_159803.dst == p)) goto LA14;
{						goto LA11;
}					}
					LA14: ;
					memset((void*)(&LOC16), 0, sizeof(LOC16));
					LOC16.ClPrc = dfssz_159687; LOC16.ClEnv = HEX3Aenvp_160020;
					LOC16.ClEnv? LOC16.ClPrc(e_159803.dst, idx, LOC16.ClEnv):((TMP45)(LOC16.ClPrc))(e_159803.dst, idx);
					(*HEX3Aenvp_160020).sz159681->data[idx] += (*HEX3Aenvp_160020).sz159681->data[e_159803.dst];
					{
						NI LOC21;
						if (!((*HEX3Aenvp_160020).sz159681->data[(*HEX3Aenvp_160020).g159654->data[idx]->data[((NI) 0)].dst] < (*HEX3Aenvp_160020).sz159681->data[e_159803.dst])) goto LA19;
{						LOC21 = 0;
						LOC21 = (*HEX3Aenvp_160020).g159654->data[idx]->data[((NI) 0)].dst;
						(*HEX3Aenvp_160020).g159654->data[idx]->data[((NI) 0)].dst = e_159803.dst;
						e_159803.dst = LOC21;
}					}
					LA19: ;
				} LA11: ;
				i_159827 += ((NI) 1);
			} LA10: ;
		}
	}
}

N_CLOSURE(void, dfshld_159830)(NI idx, NI par, NI& times, void* ClEnv) {
	TY160017* HEX3Aenvp_160024;
	HEX3Aenvp_160024 = (TY160017*) ClEnv;
	(*HEX3Aenvp_160024).ina159682->data[idx] = times;
	times += ((NI) 1);
	(*HEX3Aenvp_160024).rev159685->data[(*HEX3Aenvp_160024).ina159682->data[idx]] = idx;
	{
		Edge159419 e_160002;
		TY159416* HEX3Atmp_160006;
		memset((void*)(&e_160002), 0, sizeof(e_160002));
		HEX3Atmp_160006 = 0;
		HEX3Atmp_160006 = (*HEX3Aenvp_160024).g159654->data[idx];
		NI i_160009 = ((NI) 0);
		NI L_160011 = (HEX3Atmp_160006 ? HEX3Atmp_160006->len : 0);
		{
			while (1) {
				if (!(i_160009 < L_160011)) goto LA3;
				e_160002 = HEX3Atmp_160006->data[i_160009];
				{
					TY159831 LOC14;
					{
						if (!(e_160002.dst == par)) goto LA7;
{						goto LA4;
}					}
					LA7: ;
					{
						if (!((*HEX3Aenvp_160024).g159654->data[idx]->data[((NI) 0)].dst == e_160002.dst)) goto LA11;
{						(*HEX3Aenvp_160024).head159684->data[e_160002.dst] = (*HEX3Aenvp_160024).head159684->data[idx];
}					}
					goto LA9;
					LA11: ;
					{
						(*HEX3Aenvp_160024).head159684->data[e_160002.dst] = e_160002.dst;
					}
					LA9: ;
					memset((void*)(&LOC14), 0, sizeof(LOC14));
					LOC14.ClPrc = dfshld_159830; LOC14.ClEnv = HEX3Aenvp_160024;
					LOC14.ClEnv? LOC14.ClPrc(e_160002.dst, idx, times, LOC14.ClEnv):((TMP47)(LOC14.ClPrc))(e_160002.dst, idx, times);
				} LA4: ;
				i_160009 += ((NI) 1);
			} LA3: ;
		}
	}
	(*HEX3Aenvp_160024).outa159683->data[idx] = times;
}

N_NIMCALL(void, newheavylightdecomposition_159645)(Graph159415* g_159650, Heavylightdecomposition159200* Result) {
	TY160017* HEX3Aenv_160029;
	TY159688 LOC1;
	TY159831 LOC2;
	Heavylightdecomposition159200 LOC3;
{	HEX3Aenv_160029 = 0;
	HEX3Aenv_160029 = (TY160017*) newObj((&NTI160016), sizeof(TY160017));
	genericSeqAssign((&(*HEX3Aenv_160029).g159654), g_159650, (&NTI159415));
	asgnRefNoCycle((void**) (&(*HEX3Aenv_160029).sz159681), newseq_159664(((NI) (((*HEX3Aenv_160029).g159654 ? (*HEX3Aenv_160029).g159654->len : 0)))));
	asgnRefNoCycle((void**) (&(*HEX3Aenv_160029).ina159682), newseq_159664(((NI) (((*HEX3Aenv_160029).g159654 ? (*HEX3Aenv_160029).g159654->len : 0)))));
	asgnRefNoCycle((void**) (&(*HEX3Aenv_160029).outa159683), newseq_159664(((NI) (((*HEX3Aenv_160029).g159654 ? (*HEX3Aenv_160029).g159654->len : 0)))));
	asgnRefNoCycle((void**) (&(*HEX3Aenv_160029).head159684), newseq_159664(((NI) (((*HEX3Aenv_160029).g159654 ? (*HEX3Aenv_160029).g159654->len : 0)))));
	asgnRefNoCycle((void**) (&(*HEX3Aenv_160029).rev159685), newseq_159664(((NI) (((*HEX3Aenv_160029).g159654 ? (*HEX3Aenv_160029).g159654->len : 0)))));
	asgnRefNoCycle((void**) (&(*HEX3Aenv_160029).par159686), newseq_159664(((NI) (((*HEX3Aenv_160029).g159654 ? (*HEX3Aenv_160029).g159654->len : 0)))));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = dfssz_159687; LOC1.ClEnv = HEX3Aenv_160029;
	LOC1.ClEnv? LOC1.ClPrc(((NI) 0), ((NI) -1), LOC1.ClEnv):((TMP46)(LOC1.ClPrc))(((NI) 0), ((NI) -1));
	NI t = ((NI) 0);
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.ClPrc = dfshld_159830; LOC2.ClEnv = HEX3Aenv_160029;
	LOC2.ClEnv? LOC2.ClPrc(((NI) 0), ((NI) -1), t, LOC2.ClEnv):((TMP48)(LOC2.ClPrc))(((NI) 0), ((NI) -1), t);
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	genericSeqAssign((&LOC3.sz), (*HEX3Aenv_160029).sz159681, (&NTI159201));
	genericSeqAssign((&LOC3.ina), (*HEX3Aenv_160029).ina159682, (&NTI159201));
	genericSeqAssign((&LOC3.outa), (*HEX3Aenv_160029).outa159683, (&NTI159201));
	genericSeqAssign((&LOC3.head), (*HEX3Aenv_160029).head159684, (&NTI159201));
	genericSeqAssign((&LOC3.rev), (*HEX3Aenv_160029).rev159685, (&NTI159201));
	genericSeqAssign((&LOC3.par), (*HEX3Aenv_160029).par159686, (&NTI159201));
	genericShallowAssign((void*)Result, (void*)(&LOC3), (&NTI159200));
	goto BeforeRet;
	}BeforeRet: ;
}

N_NIMCALL(NI, lca_160062)(Heavylightdecomposition159200* self, NI u_160069, NI v_160071) {
	NI result;
	TY160073 LOC1;
	NI u;
	NI v;
{	result = 0;
	LOC1.Field0 = u_160069;
	LOC1.Field1 = v_160071;
	u = LOC1.Field0;
	v = LOC1.Field1;
	{
		while (1) {
			{
				NI LOC8;
				if (!((*self).ina->data[v] < (*self).ina->data[u])) goto LA6;
{				LOC8 = 0;
				LOC8 = u;
				u = v;
				v = LOC8;
}			}
			LA6: ;
			{
				if (!((*self).head->data[u] == (*self).head->data[v])) goto LA11;
{				result = u;
				goto BeforeRet;
}			}
			LA11: ;
			v = (*self).par->data[(*self).head->data[v]];
		}
	}
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, main_159404)(void) {
	Graph159415* g;
	Heavylightdecomposition159200 tree;
	NI N = nextint_159016(((NI) 0));
	g = newgraph_159408(N);
	{
		NI i_159532;
		Slice87882 HEX3Atmp_160105;
		i_159532 = 0;
		memset((void*)(&HEX3Atmp_160105), 0, sizeof(HEX3Atmp_160105));
		HEX3Atmp_160105 = HEX2EHEX2E_102424(((NI) 0), (N - 1));
		{
			NI x_160109;
			NI HEX3Atmp_160111;
			NI HEX3Atmp_160113;
			x_160109 = 0;
			HEX3Atmp_160111 = 0;
			HEX3Atmp_160113 = 0;
			HEX3Atmp_160111 = HEX3Atmp_160105.a;
			HEX3Atmp_160113 = HEX3Atmp_160105.b;
			NI res_160115 = HEX3Atmp_160111;
			{
				while (1) {
					if (!(res_160115 <= HEX3Atmp_160113)) goto LA4;
					x_160109 = res_160115;
					i_159532 = x_160109;
					NI k = nextint_159016(((NI) 0));
					{
						NI j_159559;
						Slice87882 HEX3Atmp_160091;
						j_159559 = 0;
						memset((void*)(&HEX3Atmp_160091), 0, sizeof(HEX3Atmp_160091));
						HEX3Atmp_160091 = HEX2EHEX2E_102424(((NI) 0), (k - 1));
						{
							NI x_160095;
							NI HEX3Atmp_160097;
							NI HEX3Atmp_160099;
							x_160095 = 0;
							HEX3Atmp_160097 = 0;
							HEX3Atmp_160099 = 0;
							HEX3Atmp_160097 = HEX3Atmp_160091.a;
							HEX3Atmp_160099 = HEX3Atmp_160091.b;
							NI res_160101 = HEX3Atmp_160097;
							{
								while (1) {
									if (!(res_160101 <= HEX3Atmp_160099)) goto LA8;
									x_160095 = res_160101;
									j_159559 = x_160095;
									NI c = nextint_159016(((NI) 0));
									addbiedge_159562(g, i_159532, c, ((NI) 1));
									res_160101 += ((NI) 1);
								} LA8: ;
							}
						}
					}
					res_160115 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	memset((void*)(&tree), 0, sizeof(tree));
	memset((void*)(&tree), 0, sizeof(tree));
	newheavylightdecomposition_159645(g, (&tree));
	NI Q = nextint_159016(((NI) 0));
	{
		NI i_160058;
		Slice87882 HEX3Atmp_160120;
		i_160058 = 0;
		memset((void*)(&HEX3Atmp_160120), 0, sizeof(HEX3Atmp_160120));
		HEX3Atmp_160120 = HEX2EHEX2E_102424(((NI) 0), (Q - 1));
		{
			NI x_160124;
			NI HEX3Atmp_160126;
			NI HEX3Atmp_160128;
			x_160124 = 0;
			HEX3Atmp_160126 = 0;
			HEX3Atmp_160128 = 0;
			HEX3Atmp_160126 = HEX3Atmp_160120.a;
			HEX3Atmp_160128 = HEX3Atmp_160120.b;
			NI res_160130 = HEX3Atmp_160126;
			{
				while (1) {
					NI LOC13;
					NimStringDesc* LOC14;
					if (!(res_160130 <= HEX3Atmp_160128)) goto LA12;
					x_160124 = res_160130;
					i_160058 = x_160124;
					NI u = nextint_159016(((NI) 0));
					NI v = nextint_159016(((NI) 0));
					LOC13 = 0;
					LOC13 = lca_160062((&tree), u, v);
					LOC14 = 0;
					LOC14 = nimIntToStr(LOC13);
					printf("%s\012", LOC14? (LOC14)->data:"nil");
					fflush(stdout);
					res_160130 += ((NI) 1);
				} LA12: ;
			}
		}
	}
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_algorithmDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_timesDatInit000();
	stdlib_mathDatInit000();
	stdlib_tablesDatInit000();
	stdlib_macrosDatInit000();
	stdlib_posixDatInit000();
	stdlib_osDatInit000();
	stdlib_setsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_futureDatInit000();
	aoj_grl_5_c_2_testDatInit000();
	stdlib_algorithmInit000();
	stdlib_sequtilsInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_timesInit000();
	stdlib_mathInit000();
	stdlib_tablesInit000();
	stdlib_macrosInit000();
	stdlib_posixInit000();
	stdlib_osInit000();
	stdlib_setsInit000();
	stdlib_streamsInit000();
	stdlib_futureInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	aoj_grl_5_c_2_testInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, aoj_grl_5_c_2_testInit000)(void) {
	main_159404();
}

NIM_EXTERNC N_NOINLINE(void, aoj_grl_5_c_2_testDatInit000)(void) {
static TNimNode* TMP35[4];
static TNimNode* TMP42[8];
static TNimNode* TMP49[6];
static TNimNode TMP3[21];
NTI159419.size = sizeof(Edge159419);
NTI159419.kind = 18;
NTI159419.base = 0;
NTI159419.flags = 3;
TMP35[0] = &TMP3[1];
TMP3[1].kind = 1;
TMP3[1].offset = offsetof(Edge159419, src);
TMP3[1].typ = (&NTI104);
TMP3[1].name = "src";
TMP35[1] = &TMP3[2];
TMP3[2].kind = 1;
TMP3[2].offset = offsetof(Edge159419, dst);
TMP3[2].typ = (&NTI104);
TMP3[2].name = "dst";
TMP35[2] = &TMP3[3];
TMP3[3].kind = 1;
TMP3[3].offset = offsetof(Edge159419, weight);
TMP3[3].typ = (&NTI104);
TMP3[3].name = "weight";
TMP35[3] = &TMP3[4];
TMP3[4].kind = 1;
TMP3[4].offset = offsetof(Edge159419, rev);
TMP3[4].typ = (&NTI104);
TMP3[4].name = "rev";
TMP3[0].len = 4; TMP3[0].kind = 2; TMP3[0].sons = &TMP35[0];
NTI159419.node = &TMP3[0];
NTI159416.size = sizeof(TY159416*);
NTI159416.kind = 24;
NTI159416.base = (&NTI159419);
NTI159416.flags = 2;
NTI159416.marker = TMP36;
NTI159415.size = sizeof(Graph159415*);
NTI159415.kind = 24;
NTI159415.base = (&NTI159416);
NTI159415.flags = 2;
NTI159415.marker = TMP37;
NTI160017.size = sizeof(TY160017);
NTI160017.kind = 18;
NTI160017.base = 0;
NTI160017.flags = 2;
TMP42[0] = &TMP3[6];
NTI160019.size = sizeof(NI);
NTI160019.kind = 20;
NTI160019.base = (&NTI104);
NTI160019.flags = 3;
TMP3[6].kind = 1;
TMP3[6].offset = offsetof(TY160017, HEX3Astate);
TMP3[6].typ = (&NTI160019);
TMP3[6].name = ":state";
TMP42[1] = &TMP3[7];
NTI159201.size = sizeof(TY159201*);
NTI159201.kind = 24;
NTI159201.base = (&NTI104);
NTI159201.flags = 2;
NTI159201.marker = TMP43;
TMP3[7].kind = 1;
TMP3[7].offset = offsetof(TY160017, par159686);
TMP3[7].typ = (&NTI159201);
TMP3[7].name = "par159686";
TMP42[2] = &TMP3[8];
TMP3[8].kind = 1;
TMP3[8].offset = offsetof(TY160017, sz159681);
TMP3[8].typ = (&NTI159201);
TMP3[8].name = "sz159681";
TMP42[3] = &TMP3[9];
TMP3[9].kind = 1;
TMP3[9].offset = offsetof(TY160017, g159654);
TMP3[9].typ = (&NTI159415);
TMP3[9].name = "g159654";
TMP42[4] = &TMP3[10];
TMP3[10].kind = 1;
TMP3[10].offset = offsetof(TY160017, ina159682);
TMP3[10].typ = (&NTI159201);
TMP3[10].name = "in_a159682";
TMP42[5] = &TMP3[11];
TMP3[11].kind = 1;
TMP3[11].offset = offsetof(TY160017, rev159685);
TMP3[11].typ = (&NTI159201);
TMP3[11].name = "rev159685";
TMP42[6] = &TMP3[12];
TMP3[12].kind = 1;
TMP3[12].offset = offsetof(TY160017, head159684);
TMP3[12].typ = (&NTI159201);
TMP3[12].name = "head159684";
TMP42[7] = &TMP3[13];
TMP3[13].kind = 1;
TMP3[13].offset = offsetof(TY160017, outa159683);
TMP3[13].typ = (&NTI159201);
TMP3[13].name = "out_a159683";
TMP3[5].len = 8; TMP3[5].kind = 2; TMP3[5].sons = &TMP42[0];
NTI160017.node = &TMP3[5];
NTI160016.size = sizeof(TY160017*);
NTI160016.kind = 22;
NTI160016.base = (&NTI160017);
NTI160016.flags = 2;
NTI160016.marker = TMP44;
NTI159200.size = sizeof(Heavylightdecomposition159200);
NTI159200.kind = 18;
NTI159200.base = 0;
NTI159200.flags = 2;
TMP49[0] = &TMP3[15];
TMP3[15].kind = 1;
TMP3[15].offset = offsetof(Heavylightdecomposition159200, sz);
TMP3[15].typ = (&NTI159201);
TMP3[15].name = "sz";
TMP49[1] = &TMP3[16];
TMP3[16].kind = 1;
TMP3[16].offset = offsetof(Heavylightdecomposition159200, ina);
TMP3[16].typ = (&NTI159201);
TMP3[16].name = "in_a";
TMP49[2] = &TMP3[17];
TMP3[17].kind = 1;
TMP3[17].offset = offsetof(Heavylightdecomposition159200, outa);
TMP3[17].typ = (&NTI159201);
TMP3[17].name = "out_a";
TMP49[3] = &TMP3[18];
TMP3[18].kind = 1;
TMP3[18].offset = offsetof(Heavylightdecomposition159200, head);
TMP3[18].typ = (&NTI159201);
TMP3[18].name = "head";
TMP49[4] = &TMP3[19];
TMP3[19].kind = 1;
TMP3[19].offset = offsetof(Heavylightdecomposition159200, rev);
TMP3[19].typ = (&NTI159201);
TMP3[19].name = "rev";
TMP49[5] = &TMP3[20];
TMP3[20].kind = 1;
TMP3[20].offset = offsetof(Heavylightdecomposition159200, par);
TMP3[20].typ = (&NTI159201);
TMP3[20].name = "par";
TMP3[14].len = 6; TMP3[14].kind = 2; TMP3[14].sons = &TMP49[0];
NTI159200.node = &TMP3[14];
}

