/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/chaemon/.choosenim/toolchains/nim-0.13.0/lib -o /home/chaemon/git/library-1/nim/tree/verify/nimcache/aoj_grl_5_a_test.o /home/chaemon/git/library-1/nim/tree/verify/nimcache/aoj_grl_5_a_test.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
typedef struct Graph159233 Graph159233;
typedef struct TY159234 TY159234;
typedef struct Edge159237 Edge159237;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47505 Cell47505;
typedef struct Cellseq47521 Cellseq47521;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Cellset47517 Cellset47517;
typedef struct Pagedesc47513 Pagedesc47513;
typedef struct Memregion29688 Memregion29688;
typedef struct Smallchunk29640 Smallchunk29640;
typedef struct Llchunk29682 Llchunk29682;
typedef struct Bigchunk29642 Bigchunk29642;
typedef struct Intset29614 Intset29614;
typedef struct Trunk29610 Trunk29610;
typedef struct Avlnode29686 Avlnode29686;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Slice88082 Slice88082;
typedef struct TY159692 TY159692;
typedef struct TY159449 TY159449;
typedef struct NimStringDesc NimStringDesc;
typedef struct Basechunk29638 Basechunk29638;
typedef struct Freecell29630 Freecell29630;
struct  Edge159237  {
NI src;
NI dst;
NI weight;
NI rev;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47505  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47521  {
NI len;
NI cap;
Cell47505** d;
};
struct  Cellset47517  {
NI counter;
NI max;
Pagedesc47513* head;
Pagedesc47513** data;
};
typedef Smallchunk29640* TY29703[512];
typedef Trunk29610* Trunkbuckets29612[256];
struct  Intset29614  {
Trunkbuckets29612 data;
};
struct  Memregion29688  {
NI minlargeobj;
NI maxlargeobj;
TY29703 freesmallchunks;
Llchunk29682* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29642* freechunkslist;
Intset29614 chunkstarts;
Avlnode29686* root;
Avlnode29686* deleted;
Avlnode29686* last;
Avlnode29686* freeavlnodes;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47521 zct;
Cellseq47521 decstack;
Cellset47517 cycleroots;
Cellseq47521 tempstack;
NI recgclock;
Memregion29688 region;
Gcstat49814 stat;
};
struct  Slice88082  {
NI a;
NI b;
};
struct  TY159692  {
NI HEX3Astate;
Graph159233* g159443;
};
struct TY159449 {
NI Field0;
NI Field1;
};
typedef struct {
N_NIMCALL_PTR(TY159449, ClPrc) (NI idx, NI par, void* ClEnv);
void* ClEnv;
} TY159446;
typedef N_CLOSURE_PTR(TY159449, TMP45) (NI idx, NI par);
typedef TY159449 TY159613[2];
typedef N_CLOSURE_PTR(TY159449, TMP46) (NI idx, NI par);
typedef N_CLOSURE_PTR(TY159449, TMP47) (NI idx, NI par);
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY29619[8];
struct  Pagedesc47513  {
Pagedesc47513* next;
NI key;
TY29619 bits;
};
struct  Basechunk29638  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29640  {
  Basechunk29638 Sup;
Smallchunk29640* next;
Smallchunk29640* prev;
Freecell29630* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29682  {
NI size;
NI acc;
Llchunk29682* next;
};
struct  Bigchunk29642  {
  Basechunk29638 Sup;
Bigchunk29642* next;
Bigchunk29642* prev;
NI align;
NF data;
};
struct  Trunk29610  {
Trunk29610* next;
NI key;
TY29619 bits;
};
typedef Avlnode29686* TY29693[2];
struct  Avlnode29686  {
TY29693 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell29630  {
Freecell29630* next;
NI zerofield;
};
struct TY159234 {
  TGenericSeq Sup;
  Edge159237 data[SEQ_DECL_SIZE];
};
struct Graph159233 {
  TGenericSeq Sup;
  TY159234* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, main_159222)(void);
N_NIMCALL(NI, nextint_159016)(NI base);
N_NIMCALL(Graph159233*, newgraph_159226)(NI n);
N_NIMCALL(Graph159233*, newseq_159272)(NI len);
N_NIMCALL(void, TMP36)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP37)(void* p, NI op);
N_NIMCALL(TY159234*, newseq_159254)(NI len);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell47505*, usrtocell_51440)(void* usr);
static N_INLINE(void, rtladdzct_53001)(Cell47505* c);
N_NOINLINE(void, addzct_51417)(Cellseq47521* s, Cell47505* c);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_84004, TNimType* mt);
static N_INLINE(Slice88082, HEX2EHEX2E_102424)(NI a, NI b);
N_NIMCALL(void, addbiedge_159355)(Graph159233** g, NI src, NI dst, NI weight);
N_NIMCALL(Edge159237, newedge_159377)(NI src, NI dst, NI weight, NI rev);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NI, treediameter_159438)(Graph159233* g);
N_NIMCALL(void, TMP44)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_CLOSURE(TY159449, dfs_159445)(NI idx, NI par, void* ClEnv);
N_NIMCALL(TY159449, max_159618)(TY159449* x, NI xLen0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, aoj_grl_5_a_testInit000)(void);
NIM_EXTERNC N_NOINLINE(void, aoj_grl_5_a_testDatInit000)(void);
TNimType NTI159237; /* Edge */
extern TNimType NTI104; /* int */
TNimType NTI159234; /* seq[Edge[system.int]] */
TNimType NTI159233; /* Graph */
extern Gcheap49818 gch_49859;
TNimType NTI159692; /* object */
TNimType NTI159694; /* range -1..0(int) */
TNimType NTI159691; /* ref object */

N_NIMCALL(NI, nextint_159016)(NI base) {
	NI result;
	result = 0;
	scanf("%lld", (&result));
	result -= base;
	return result;
}
N_NIMCALL(void, TMP36)(void* p, NI op) {
	TY159234* a;
	NI LOC1;
	a = (TY159234*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}
N_NIMCALL(void, TMP37)(void* p, NI op) {
	Graph159233* a;
	NI LOC1;
	a = (Graph159233*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(Cell47505*, usrtocell_51440)(void* usr) {
	Cell47505* result;
	result = 0;
	result = ((Cell47505*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47505))))));
	return result;
}

static N_INLINE(void, rtladdzct_53001)(Cell47505* c) {
	addzct_51417((&gch_49859.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		Cell47505* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_51440(src);
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell47505* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_51440((*dest));
		{
			(*c).refcount -= ((NI) 8);
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			rtladdzct_53001(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(Graph159233*, newgraph_159226)(NI n) {
	Graph159233* result_159246;
	Graph159233* result_159248;
{	result_159246 = 0;
	result_159248 = newseq_159272(((NI) (n)));
	{
		NI i_159250;
		NI HEX3Atmp_159317;
		NI res_159320;
		i_159250 = 0;
		HEX3Atmp_159317 = 0;
		HEX3Atmp_159317 = (n - 1);
		res_159320 = ((NI) 0);
		{
			while (1) {
				if (!(res_159320 <= HEX3Atmp_159317)) goto LA3;
				i_159250 = res_159320;
				asgnRefNoCycle((void**) (&result_159248->data[i_159250]), newseq_159254(((NI) 0)));
				res_159320 += ((NI) 1);
			} LA3: ;
		}
	}
	genericSeqAssign((&result_159246), result_159248, (&NTI159233));
	goto BeforeRet;
	}BeforeRet: ;
	return result_159246;
}

static N_INLINE(Slice88082, HEX2EHEX2E_102424)(NI a, NI b) {
	Slice88082 result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

N_NIMCALL(Edge159237, newedge_159377)(NI src, NI dst, NI weight, NI rev) {
	Edge159237 result;
	Edge159237 e;
{	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&e), 0, sizeof(e));
	e.src = src;
	e.dst = dst;
	e.weight = weight;
	e.rev = rev;
	result = e;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, addbiedge_159355)(Graph159233** g, NI src, NI dst, NI weight) {
	Edge159237 LOC1;
	Edge159237 LOC2;
	LOC1 = newedge_159377(src, dst, weight, ((*g)->data[dst] ? (*g)->data[dst]->Sup.len : 0));
	(*g)->data[src] = (TY159234*) incrSeqV2(&((*g)->data[src])->Sup, sizeof(Edge159237));
	(*g)->data[src]->data[(*g)->data[src]->Sup.len] = LOC1;
	++(*g)->data[src]->Sup.len;
	LOC2 = newedge_159377(dst, src, weight, (NI)(((*g)->data[src] ? (*g)->data[src]->Sup.len : 0) - ((NI) 1)));
	(*g)->data[dst] = (TY159234*) incrSeqV2(&((*g)->data[dst])->Sup, sizeof(Edge159237));
	(*g)->data[dst]->data[(*g)->data[dst]->Sup.len] = LOC2;
	++(*g)->data[dst]->Sup.len;
}
N_NIMCALL(void, TMP44)(void* p, NI op) {
	TY159692* a;
	a = (TY159692*)p;
	nimGCvisit((void*)(*a).g159443, op);
}

N_CLOSURE(TY159449, dfs_159445)(NI idx, NI par, void* ClEnv) {
	TY159449 result;
	TY159692* HEX3Aenvp_159695;
	memset((void*)(&result), 0, sizeof(result));
	HEX3Aenvp_159695 = (TY159692*) ClEnv;
	result.Field1 = idx;
	{
		Edge159237 e_159602;
		TY159234* HEX3Atmp_159683;
		NI i_159686;
		NI L_159688;
		memset((void*)(&e_159602), 0, sizeof(e_159602));
		HEX3Atmp_159683 = 0;
		HEX3Atmp_159683 = (*HEX3Aenvp_159695).g159443->data[idx];
		i_159686 = ((NI) 0);
		L_159688 = (HEX3Atmp_159683 ? HEX3Atmp_159683->Sup.len : 0);
		{
			while (1) {
				if (!(i_159686 < L_159688)) goto LA3;
				e_159602 = HEX3Atmp_159683->data[i_159686];
				{
					TY159449 cost;
					TY159446 LOC9;
					TY159613 LOC10;
					{
						if (!(e_159602.dst == par)) goto LA7;
						goto LA4;
					}
					LA7: ;
					memset((void*)(&LOC9), 0, sizeof(LOC9));
					LOC9.ClPrc = dfs_159445; LOC9.ClEnv = HEX3Aenvp_159695;
					cost = LOC9.ClEnv? LOC9.ClPrc(e_159602.dst, idx, LOC9.ClEnv):((TMP45)(LOC9.ClPrc))(e_159602.dst, idx);
					cost.Field0 += e_159602.weight;
					LOC10[0] = result;
					LOC10[1] = cost;
					result = max_159618(LOC10, 2);
				} LA4: ;
				i_159686 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

N_NIMCALL(NI, treediameter_159438)(Graph159233* g) {
	NI result;
	TY159692* HEX3Aenv_159697;
	TY159449 p;
	TY159446 LOC1;
	TY159449 q;
	TY159446 LOC2;
{	result = 0;
	HEX3Aenv_159697 = 0;
	HEX3Aenv_159697 = (TY159692*) newObj((&NTI159691), sizeof(TY159692));
	genericSeqAssign((&(*HEX3Aenv_159697).g159443), g, (&NTI159233));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = dfs_159445; LOC1.ClEnv = HEX3Aenv_159697;
	p = LOC1.ClEnv? LOC1.ClPrc(((NI) 0), ((NI) -1), LOC1.ClEnv):((TMP46)(LOC1.ClPrc))(((NI) 0), ((NI) -1));
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.ClPrc = dfs_159445; LOC2.ClEnv = HEX3Aenv_159697;
	q = LOC2.ClEnv? LOC2.ClPrc(p.Field1, ((NI) -1), LOC2.ClEnv):((TMP47)(LOC2.ClPrc))(p.Field1, ((NI) -1));
	result = q.Field0;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, main_159222)(void) {
	NI N;
	Graph159233* g;
	NI LOC5;
	NimStringDesc* LOC6;
	N = nextint_159016(((NI) 0));
	g = newgraph_159226(N);
	{
		NI i_159350;
		Slice88082 HEX3Atmp_159701;
		i_159350 = 0;
		memset((void*)(&HEX3Atmp_159701), 0, sizeof(HEX3Atmp_159701));
		HEX3Atmp_159701 = HEX2EHEX2E_102424(((NI) 1), (N - 1));
		{
			NI x_159705;
			NI HEX3Atmp_159707;
			NI HEX3Atmp_159709;
			NI res_159711;
			x_159705 = 0;
			HEX3Atmp_159707 = 0;
			HEX3Atmp_159709 = 0;
			HEX3Atmp_159707 = HEX3Atmp_159701.a;
			HEX3Atmp_159709 = HEX3Atmp_159701.b;
			res_159711 = HEX3Atmp_159707;
			{
				while (1) {
					NI x;
					NI y;
					NI z;
					if (!(res_159711 <= HEX3Atmp_159709)) goto LA4;
					x_159705 = res_159711;
					i_159350 = x_159705;
					x = nextint_159016(((NI) 0));
					y = nextint_159016(((NI) 0));
					z = nextint_159016(((NI) 0));
					addbiedge_159355((&g), x, y, z);
					res_159711 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	LOC5 = 0;
	LOC5 = treediameter_159438(g);
	LOC6 = 0;
	LOC6 = nimIntToStr(LOC5);
	printf("%s\012", LOC6? (LOC6)->data:"nil");
	fflush(stdout);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_algorithmDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_timesDatInit000();
	stdlib_mathDatInit000();
	stdlib_tablesDatInit000();
	stdlib_macrosDatInit000();
	stdlib_posixDatInit000();
	stdlib_osDatInit000();
	stdlib_setsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_futureDatInit000();
	aoj_grl_5_a_testDatInit000();
	stdlib_algorithmInit000();
	stdlib_sequtilsInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_timesInit000();
	stdlib_mathInit000();
	stdlib_tablesInit000();
	stdlib_macrosInit000();
	stdlib_posixInit000();
	stdlib_osInit000();
	stdlib_setsInit000();
	stdlib_streamsInit000();
	stdlib_futureInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	aoj_grl_5_a_testInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, aoj_grl_5_a_testInit000)(void) {
	main_159222();
}

NIM_EXTERNC N_NOINLINE(void, aoj_grl_5_a_testDatInit000)(void) {
static TNimNode* TMP35[4];
static TNimNode* TMP43[2];
static TNimNode TMP3[8];
NTI159237.size = sizeof(Edge159237);
NTI159237.kind = 18;
NTI159237.base = 0;
NTI159237.flags = 3;
TMP35[0] = &TMP3[1];
TMP3[1].kind = 1;
TMP3[1].offset = offsetof(Edge159237, src);
TMP3[1].typ = (&NTI104);
TMP3[1].name = "src";
TMP35[1] = &TMP3[2];
TMP3[2].kind = 1;
TMP3[2].offset = offsetof(Edge159237, dst);
TMP3[2].typ = (&NTI104);
TMP3[2].name = "dst";
TMP35[2] = &TMP3[3];
TMP3[3].kind = 1;
TMP3[3].offset = offsetof(Edge159237, weight);
TMP3[3].typ = (&NTI104);
TMP3[3].name = "weight";
TMP35[3] = &TMP3[4];
TMP3[4].kind = 1;
TMP3[4].offset = offsetof(Edge159237, rev);
TMP3[4].typ = (&NTI104);
TMP3[4].name = "rev";
TMP3[0].len = 4; TMP3[0].kind = 2; TMP3[0].sons = &TMP35[0];
NTI159237.node = &TMP3[0];
NTI159234.size = sizeof(TY159234*);
NTI159234.kind = 24;
NTI159234.base = (&NTI159237);
NTI159234.flags = 2;
NTI159234.marker = TMP36;
NTI159233.size = sizeof(Graph159233*);
NTI159233.kind = 24;
NTI159233.base = (&NTI159234);
NTI159233.flags = 2;
NTI159233.marker = TMP37;
NTI159692.size = sizeof(TY159692);
NTI159692.kind = 18;
NTI159692.base = 0;
NTI159692.flags = 2;
TMP43[0] = &TMP3[6];
NTI159694.size = sizeof(NI);
NTI159694.kind = 20;
NTI159694.base = (&NTI104);
NTI159694.flags = 3;
TMP3[6].kind = 1;
TMP3[6].offset = offsetof(TY159692, HEX3Astate);
TMP3[6].typ = (&NTI159694);
TMP3[6].name = ":state";
TMP43[1] = &TMP3[7];
TMP3[7].kind = 1;
TMP3[7].offset = offsetof(TY159692, g159443);
TMP3[7].typ = (&NTI159233);
TMP3[7].name = "g159443";
TMP3[5].len = 2; TMP3[5].kind = 2; TMP3[5].sons = &TMP43[0];
NTI159692.node = &TMP3[5];
NTI159691.size = sizeof(TY159692*);
NTI159691.kind = 22;
NTI159691.base = (&NTI159692);
NTI159691.flags = 2;
NTI159691.marker = TMP44;
}

