/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   g++ -c  -w -w -fpermissive -O3 -fno-strict-aliasing  -I/home/chaemon/.choosenim/toolchains/nim-0.13.0/lib -o /home/chaemon/git/library-1/nim/tree/verify/nimcache/stdlib_sequtils.o /home/chaemon/git/library-1/nim/tree/verify/nimcache/stdlib_sequtils.cpp */
#define NIM_INTBITS 64

#include "nimbase.h"
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void) {
}

