/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   g++ -c  -w -w -fpermissive -O3 -fno-strict-aliasing  -I/home/chaemon/.choosenim/toolchains/nim-0.13.0/lib -o /home/chaemon/git/library-1/nim/tree/verify/nimcache/stdlib_os.o /home/chaemon/git/library-1/nim/tree/verify/nimcache/stdlib_os.cpp */
#define NIM_INTBITS 64

#include "nimbase.h"
struct TY143202;
struct NimStringDesc;
struct TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY143202 : TGenericSeq {
  NimStringDesc* data[SEQ_DECL_SIZE];
};
NIM_BOOL envcomputed_143201;
TY143202* environment_143203;
extern NCSTRING* environ;
extern int cmdCount;
extern NCSTRING* cmdLine;
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void) {
}

