/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/chaemon/.choosenim/toolchains/nim-0.13.0/lib -o /home/chaemon/git/library-1/nim/math/verify/nimcache/aoj_dpl_5_i_test.o /home/chaemon/git/library-1/nim/math/verify/nimcache/aoj_dpl_5_i_test.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Mint159105 Mint159105;
typedef struct Combination159493 Combination159493;
typedef struct TY159499 TY159499;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY159201 TY159201;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Mint159105  {
NI v;
};
struct  Combination159493  {
NI sz;
TY159499* facta;
TY159499* rfacta;
TY159499* inva;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY159201 {
Mint159105 Field0;
NI Field1;
};
struct TY159499 {
  TGenericSeq Sup;
  Mint159105 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, main_159472)(void);
N_NIMCALL(NI, nextint_159016)(NI base);
N_NIMCALL(NimStringDesc*, HEX24_159192)(Mint159105 a);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(Mint159105, stirlingnumbersecond_159477)(NI n, NI k);
N_NIMCALL(void, initcombination_159486)(NI sz, Combination159493* Result);
N_NIMCALL(TY159499*, newseq_159514)(NI len);
N_NIMCALL(void, TMP35)(void* p, NI op);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_84004, TNimType* mt);
N_NIMCALL(Mint159105, init_159610)(Mint159105 self, NI a);
N_NIMCALL(Mint159105, initmint_159205)(NI a_159209);
N_NIMCALL(Mint159105, HEX2A_159654)(Mint159105 a, NI b);
N_NIMCALL(void, HEX2AHEX3D_159664)(Mint159105* a, NI b);
static N_INLINE(void, HEX2AHEX3D_159233)(NI* x, NI y);
N_NIMCALL(void, HEX2FHEX3D_159691)(Mint159105* a, Mint159105 b);
N_NIMCALL(NI, invmod_159272)(NI a, NI m);
N_NIMCALL(NI, extgcd_159254)(NI a, NI b, NI* x, NI* y);
N_NIMCALL(Mint159105, initmint_159125)(Mint159105 a);
N_NIMCALL(Mint159105, HEX2A_159741)(Mint159105 a, Mint159105 b);
N_NIMCALL(void, HEX2AHEX3D_159225)(Mint159105* a, Mint159105 b);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(Mint159105, pow_159196)(Mint159105 x_159198, NI n_159199);
N_NIMCALL(Mint159105, C_159835)(Combination159493* self, NI p, NI q);
N_NIMCALL(Mint159105, fact_159848)(Combination159493* self, NI k);
N_NIMCALL(Mint159105, rfact_159868)(Combination159493* self, NI k);
N_NIMCALL(void, HEX2DHEX3D_159930)(Mint159105* a, Mint159105 b);
N_NIMCALL(void, HEX2BHEX3D_159957)(Mint159105* a, Mint159105 b);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, aoj_dpl_5_i_testInit000)(void);
NIM_EXTERNC N_NOINLINE(void, aoj_dpl_5_i_testDatInit000)(void);
TNimType NTI159105; /* Mint */
extern TNimType NTI104; /* int */
TNimType NTI159499; /* seq[Mint] */

N_NIMCALL(NI, nextint_159016)(NI base) {
	NI result;
	result = 0;
	scanf("%lld", (&result));
	result -= base;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_159192)(Mint159105 a) {
	NimStringDesc* result;
{	result = 0;
	result = nimIntToStr(a.v);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP35)(void* p, NI op) {
	TY159499* a;
	NI LOC1;
	a = (TY159499*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(Mint159105, initmint_159205)(NI a_159209) {
	Mint159105 result;
	NI a;
	Mint159105 LOC5;
{	memset((void*)(&result), 0, sizeof(result));
	a = a_159209;
	a = ((NI) ((NI)(a % ((NI) 1000000007))));
	{
		if (!(a < ((NI) 0))) goto LA3;
		a += ((NI) 1000000007);
	}
	LA3: ;
	memset((void*)(&LOC5), 0, sizeof(LOC5));
	LOC5.v = a;
	result = LOC5;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Mint159105, init_159610)(Mint159105 self, NI a) {
	Mint159105 result;
	memset((void*)(&result), 0, sizeof(result));
	result = initmint_159205(a);
	return result;
}

static N_INLINE(void, HEX2AHEX3D_159233)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

N_NIMCALL(void, HEX2AHEX3D_159664)(Mint159105* a, NI b) {
	Mint159105 LOC1;
	LOC1 = initmint_159205(b);
	HEX2AHEX3D_159233((&(*a).v), LOC1.v);
	(*a).v = ((NI) ((NI)((*a).v % ((NI) 1000000007))));
}

N_NIMCALL(Mint159105, HEX2A_159654)(Mint159105 a, NI b) {
	Mint159105 result;
	Mint159105 c;
{	memset((void*)(&result), 0, sizeof(result));
	c = a;
	HEX2AHEX3D_159664((&c), b);
	result = c;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, extgcd_159254)(NI a, NI b, NI* x, NI* y) {
	NI result;
	NI g;
{	result = 0;
	g = a;
	(*x) = ((NI) 1);
	(*y) = ((NI) 0);
	{
		if (!!((b == ((NI) 0)))) goto LA3;
		g = extgcd_159254(b, (NI)(a % b), y, x);
		(*y) -= (NI)((NI)(a / b) * (*x));
	}
	LA3: ;
	result = g;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, invmod_159272)(NI a, NI m) {
	NI result;
	NI x;
	NI y;
{	result = 0;
	x = 0;
	y = 0;
	{
		NI LOC3;
		LOC3 = 0;
		LOC3 = extgcd_159254(a, m, (&x), (&y));
		if (!(LOC3 == ((NI) 1))) goto LA4;
		result = (NI)((NI)(x + m) % m);
		goto BeforeRet;
	}
	goto LA1;
	LA4: ;
	{
		result = ((NI) 0);
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Mint159105, initmint_159125)(Mint159105 a) {
	Mint159105 result;
{	memset((void*)(&result), 0, sizeof(result));
	result = a;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, HEX2FHEX3D_159691)(Mint159105* a, Mint159105 b) {
	Mint159105 LOC1;
	NI LOC2;
	LOC1 = initmint_159125(b);
	LOC2 = 0;
	LOC2 = invmod_159272(LOC1.v, ((NI) 1000000007));
	HEX2AHEX3D_159233((&(*a).v), LOC2);
	(*a).v = ((NI) ((NI)((*a).v % ((NI) 1000000007))));
}

N_NIMCALL(void, HEX2AHEX3D_159225)(Mint159105* a, Mint159105 b) {
	Mint159105 LOC1;
	LOC1 = initmint_159125(b);
	HEX2AHEX3D_159233((&(*a).v), LOC1.v);
	(*a).v = ((NI) ((NI)((*a).v % ((NI) 1000000007))));
}

N_NIMCALL(Mint159105, HEX2A_159741)(Mint159105 a, Mint159105 b) {
	Mint159105 result;
	Mint159105 c;
{	memset((void*)(&result), 0, sizeof(result));
	c = a;
	HEX2AHEX3D_159225((&c), b);
	result = c;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, initcombination_159486)(NI sz, Combination159493* Result) {
	TY159499* facta;
	TY159499* result_159510;
	TY159499* rfacta;
	TY159499* result_159550;
	TY159499* inva;
	TY159499* result_159580;
	Mint159105 LOC13;
	Mint159105 LOC14;
	Mint159105 LOC15;
	Combination159493 LOC25;
{	result_159510 = newseq_159514(((NI) ((NI)(sz + ((NI) 1)))));
	{
		NI i_159512;
		NI HEX3Atmp_159763;
		NI res_159766;
		i_159512 = 0;
		HEX3Atmp_159763 = 0;
		HEX3Atmp_159763 = ((NI)(sz + ((NI) 1)) - 1);
		res_159766 = ((NI) 0);
		{
			while (1) {
				Mint159105 LOC4;
				if (!(res_159766 <= HEX3Atmp_159763)) goto LA3;
				i_159512 = res_159766;
				memset((void*)(&LOC4), 0, sizeof(LOC4));
				result_159510->data[i_159512] = LOC4;
				res_159766 += ((NI) 1);
			} LA3: ;
		}
	}
	genericSeqAssign((&facta), result_159510, (&NTI159499));
	result_159550 = newseq_159514(((NI) ((NI)(sz + ((NI) 1)))));
	{
		NI i_159552;
		NI HEX3Atmp_159772;
		NI res_159775;
		i_159552 = 0;
		HEX3Atmp_159772 = 0;
		HEX3Atmp_159772 = ((NI)(sz + ((NI) 1)) - 1);
		res_159775 = ((NI) 0);
		{
			while (1) {
				Mint159105 LOC8;
				if (!(res_159775 <= HEX3Atmp_159772)) goto LA7;
				i_159552 = res_159775;
				memset((void*)(&LOC8), 0, sizeof(LOC8));
				result_159550->data[i_159552] = LOC8;
				res_159775 += ((NI) 1);
			} LA7: ;
		}
	}
	genericSeqAssign((&rfacta), result_159550, (&NTI159499));
	result_159580 = newseq_159514(((NI) ((NI)(sz + ((NI) 1)))));
	{
		NI i_159582;
		NI HEX3Atmp_159781;
		NI res_159784;
		i_159582 = 0;
		HEX3Atmp_159781 = 0;
		HEX3Atmp_159781 = ((NI)(sz + ((NI) 1)) - 1);
		res_159784 = ((NI) 0);
		{
			while (1) {
				Mint159105 LOC12;
				if (!(res_159784 <= HEX3Atmp_159781)) goto LA11;
				i_159582 = res_159784;
				memset((void*)(&LOC12), 0, sizeof(LOC12));
				result_159580->data[i_159582] = LOC12;
				res_159784 += ((NI) 1);
			} LA11: ;
		}
	}
	genericSeqAssign((&inva), result_159580, (&NTI159499));
	memset((void*)(&LOC13), 0, sizeof(LOC13));
	facta->data[((NI) 0)] = init_159610(LOC13, ((NI) 1));
	memset((void*)(&LOC14), 0, sizeof(LOC14));
	rfacta->data[sz] = init_159610(LOC14, ((NI) 1));
	memset((void*)(&LOC15), 0, sizeof(LOC15));
	inva->data[((NI) 0)] = init_159610(LOC15, ((NI) 1));
	{
		NI i_159652;
		NI res_159794;
		i_159652 = 0;
		res_159794 = ((NI) 1);
		{
			while (1) {
				if (!(res_159794 <= sz)) goto LA18;
				i_159652 = res_159794;
				facta->data[i_159652] = HEX2A_159654(facta->data[(NI)(i_159652 - ((NI) 1))], i_159652);
				res_159794 += ((NI) 1);
			} LA18: ;
		}
	}
	HEX2FHEX3D_159691((&rfacta->data[sz]), facta->data[sz]);
	{
		NI i_159720;
		NI HEX3Atmp_159799;
		NI res_159802;
		i_159720 = 0;
		HEX3Atmp_159799 = 0;
		HEX3Atmp_159799 = (NI)(sz - ((NI) 1));
		res_159802 = HEX3Atmp_159799;
		{
			while (1) {
				if (!(((NI) 0) <= res_159802)) goto LA21;
				i_159720 = res_159802;
				rfacta->data[i_159720] = HEX2A_159654(rfacta->data[(NI)(i_159720 + ((NI) 1))], (NI)(i_159720 + ((NI) 1)));
				res_159802 -= ((NI) 1);
			} LA21: ;
		}
	}
	{
		NI i_159739;
		NI res_159809;
		i_159739 = 0;
		res_159809 = ((NI) 1);
		{
			while (1) {
				if (!(res_159809 <= sz)) goto LA24;
				i_159739 = res_159809;
				inva->data[i_159739] = HEX2A_159741(rfacta->data[i_159739], facta->data[(NI)(i_159739 - ((NI) 1))]);
				res_159809 += ((NI) 1);
			} LA24: ;
		}
	}
	memset((void*)(&LOC25), 0, sizeof(LOC25));
	memset((void*)(&LOC25), 0, sizeof(LOC25));
	LOC25.sz = sz;
	genericSeqAssign((&LOC25.facta), facta, (&NTI159499));
	genericSeqAssign((&LOC25.rfacta), rfacta, (&NTI159499));
	genericSeqAssign((&LOC25.inva), inva, (&NTI159499));
	(*Result).sz = LOC25.sz;
	unsureAsgnRef((void**) (&(*Result).facta), LOC25.facta);
	unsureAsgnRef((void**) (&(*Result).rfacta), LOC25.rfacta);
	unsureAsgnRef((void**) (&(*Result).inva), LOC25.inva);
	goto BeforeRet;
	}BeforeRet: ;
}

N_NIMCALL(Mint159105, pow_159196)(Mint159105 x_159198, NI n_159199) {
	Mint159105 result;
	TY159201 LOC1;
	Mint159105 x;
	NI n;
	memset((void*)(&result), 0, sizeof(result));
	LOC1.Field0 = x_159198;
	LOC1.Field1 = n_159199;
	x = LOC1.Field0;
	n = LOC1.Field1;
	result = initmint_159205(((NI) 1));
	{
		while (1) {
			if (!(((NI) 0) < n)) goto LA3;
			{
				if (!(((NI) 0) < ((NI) ((NI)(n & ((NI) 1)))))) goto LA6;
				HEX2AHEX3D_159225((&result), x);
			}
			LA6: ;
			HEX2AHEX3D_159225((&x), x);
			n = (NI)((NU64)(n) >> (NU64)(((NI) 1)));
		} LA3: ;
	}
	return result;
}

N_NIMCALL(Mint159105, fact_159848)(Combination159493* self, NI k) {
	Mint159105 result;
{	memset((void*)(&result), 0, sizeof(result));
	{
		while (1) {
			if (!((*self).sz < k)) goto LA2;
			initcombination_159486((NI)((*self).sz * ((NI) 2)), (&(*self)));
		} LA2: ;
	}
	result = (*self).facta->data[k];
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Mint159105, rfact_159868)(Combination159493* self, NI k) {
	Mint159105 result;
	memset((void*)(&result), 0, sizeof(result));
	{
		while (1) {
			if (!((*self).sz < k)) goto LA2;
			initcombination_159486((NI)((*self).sz * ((NI) 2)), (&(*self)));
		} LA2: ;
	}
	result = (*self).rfacta->data[k];
	return result;
}

N_NIMCALL(Mint159105, C_159835)(Combination159493* self, NI p, NI q) {
	Mint159105 result;
	Mint159105 LOC8;
	Mint159105 LOC9;
	Mint159105 LOC10;
	Mint159105 LOC11;
{	memset((void*)(&result), 0, sizeof(result));
	{
		NIM_BOOL LOC3;
		Mint159105 LOC7;
		LOC3 = 0;
		LOC3 = (q < ((NI) 0));
		if (LOC3) goto LA4;
		LOC3 = (p < q);
		LA4: ;
		if (!LOC3) goto LA5;
		memset((void*)(&LOC7), 0, sizeof(LOC7));
		result = LOC7;
		goto BeforeRet;
	}
	LA5: ;
	LOC8 = fact_159848(self, p);
	LOC9 = rfact_159868(self, q);
	LOC10 = HEX2A_159741(LOC8, LOC9);
	LOC11 = rfact_159868(self, (NI)(p - q));
	result = HEX2A_159741(LOC10, LOC11);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, HEX2DHEX3D_159930)(Mint159105* a, Mint159105 b) {
	Mint159105 LOC1;
	LOC1 = initmint_159125(b);
	(*a).v -= LOC1.v;
	{
		if (!((*a).v < ((NI) 0))) goto LA4;
		(*a).v += ((NI) 1000000007);
	}
	LA4: ;
}

N_NIMCALL(void, HEX2BHEX3D_159957)(Mint159105* a, Mint159105 b) {
	Mint159105 LOC1;
	LOC1 = initmint_159125(b);
	(*a).v += LOC1.v;
	{
		if (!(((NI) 1000000007) <= (*a).v)) goto LA4;
		(*a).v -= ((NI) 1000000007);
	}
	LA4: ;
}

N_NIMCALL(Mint159105, stirlingnumbersecond_159477)(NI n, NI k) {
	Mint159105 result;
	Combination159493 table;
	Mint159105 LOC1;
	Mint159105 LOC14;
	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&table), 0, sizeof(table));
	memset((void*)(&table), 0, sizeof(table));
	initcombination_159486(k, (&table));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	result = LOC1;
	{
		NI i_159824;
		NI res_160009;
		i_159824 = 0;
		res_160009 = ((NI) 0);
		{
			while (1) {
				Mint159105 a;
				Mint159105 LOC5;
				Mint159105 LOC6;
				Mint159105 LOC7;
				Mint159105 LOC8;
				if (!(res_160009 <= k)) goto LA4;
				i_159824 = res_160009;
				memset((void*)(&LOC5), 0, sizeof(LOC5));
				LOC6 = init_159610(LOC5, i_159824);
				LOC7 = pow_159196(LOC6, n);
				LOC8 = C_159835((&table), k, i_159824);
				a = HEX2A_159741(LOC7, LOC8);
				{
					if (!(((NI) 0) < ((NI) ((NI)((NI)(k - i_159824) & ((NI) 1)))))) goto LA11;
					HEX2DHEX3D_159930((&result), a);
				}
				goto LA9;
				LA11: ;
				{
					HEX2BHEX3D_159957((&result), a);
				}
				LA9: ;
				res_160009 += ((NI) 1);
			} LA4: ;
		}
	}
	LOC14 = rfact_159868((&table), k);
	HEX2AHEX3D_159225((&result), LOC14);
	return result;
}

N_NIMCALL(void, main_159472)(void) {
	NI N;
	NI K;
	Mint159105 LOC1;
	NimStringDesc* LOC2;
	N = nextint_159016(((NI) 0));
	K = nextint_159016(((NI) 0));
	LOC1 = stirlingnumbersecond_159477(N, K);
	LOC2 = 0;
	LOC2 = HEX24_159192(LOC1);
	printf("%s\012", LOC2? (LOC2)->data:"nil");
	fflush(stdout);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_algorithmDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_timesDatInit000();
	stdlib_mathDatInit000();
	stdlib_tablesDatInit000();
	stdlib_macrosDatInit000();
	stdlib_posixDatInit000();
	stdlib_osDatInit000();
	stdlib_setsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_futureDatInit000();
	aoj_dpl_5_i_testDatInit000();
	stdlib_algorithmInit000();
	stdlib_sequtilsInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_timesInit000();
	stdlib_mathInit000();
	stdlib_tablesInit000();
	stdlib_macrosInit000();
	stdlib_posixInit000();
	stdlib_osInit000();
	stdlib_setsInit000();
	stdlib_streamsInit000();
	stdlib_futureInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	aoj_dpl_5_i_testInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, aoj_dpl_5_i_testInit000)(void) {
	main_159472();
}

NIM_EXTERNC N_NOINLINE(void, aoj_dpl_5_i_testDatInit000)(void) {
static TNimNode TMP3[1];
NTI159105.size = sizeof(Mint159105);
NTI159105.kind = 18;
NTI159105.base = 0;
NTI159105.flags = 3;
TMP3[0].kind = 1;
TMP3[0].offset = offsetof(Mint159105, v);
TMP3[0].typ = (&NTI104);
TMP3[0].name = "v";
NTI159105.node = &TMP3[0];
NTI159499.size = sizeof(TY159499*);
NTI159499.kind = 24;
NTI159499.base = (&NTI159105);
NTI159499.flags = 2;
NTI159499.marker = TMP35;
}

