/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/chaemon/.choosenim/toolchains/nim-0.13.0/lib -o /home/chaemon/git/library-1/nim/math/verify/nimcache/aoj_ntl_1_a_test.o /home/chaemon/git/library-1/nim/math/verify/nimcache/aoj_ntl_1_a_test.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Orderedtable159110 Orderedtable159110;
typedef struct Orderedkeyvaluepairseq159113 Orderedkeyvaluepairseq159113;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Orderedkeyvaluepair159116 Orderedkeyvaluepair159116;
typedef struct Slice88082 Slice88082;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* TY159653[2];
struct  Orderedtable159110  {
Orderedkeyvaluepairseq159113* data;
NI counter;
NI first;
NI last;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct Orderedkeyvaluepair159116 {
NI Field0;
NI Field1;
NI Field2;
NI Field3;
};
struct  Slice88082  {
NI a;
NI b;
};
struct Orderedkeyvaluepairseq159113 {
  TGenericSeq Sup;
  Orderedkeyvaluepair159116 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, main_159650)(void);
N_NIMCALL(NI, nextint_159016)(NI base);
N_NIMCALL(void, write_15505)(FILE* f, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, primefactor_159102)(NI n_159104, Orderedtable159110* Result);
N_NIMCALL(void, initorderedtable_159137)(NI initialsize, Orderedtable159110* Result);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX5BHEX5DHEX3D_159213)(Orderedtable159110* t, NI key, NI val);
N_NIMCALL(NI*, HEX5BHEX5D_159384)(Orderedtable159110* t, NI key);
static N_INLINE(NIM_BOOL, isfilled_118263)(NI hcode);
static N_INLINE(Slice88082, HEX2EHEX2E_102424)(NI a, NI b);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, aoj_ntl_1_a_testInit000)(void);
NIM_EXTERNC N_NOINLINE(void, aoj_ntl_1_a_testDatInit000)(void);
STRING_LITERAL(TMP40, ":", 1);
STRING_LITERAL(TMP48, " ", 1);
STRING_LITERAL(TMP49, "", 0);
extern TNimType NTI159110; /* OrderedTable */

N_NIMCALL(NI, nextint_159016)(NI base) {
	NI result;
	result = 0;
	scanf("%lld", (&result));
	result -= base;
	return result;
}

N_NIMCALL(void, primefactor_159102)(NI n_159104, Orderedtable159110* Result) {
	NI n;
	NI i;
	n = n_159104;
	genericReset((void*)Result, (&NTI159110));
	initorderedtable_159137(((NI) 64), Result);
	i = ((NI) 2);
	{
		while (1) {
			{
				if (!(n < (NI)(i * i))) goto LA5;
				goto LA1;
			}
			LA5: ;
			HEX5BHEX5DHEX3D_159213(Result, i, ((NI) 0));
			{
				while (1) {
					NI* LOC9;
					if (!((NI)(n % i) == ((NI) 0))) goto LA8;
					LOC9 = 0;
					LOC9 = HEX5BHEX5D_159384(Result, i);
					(*LOC9) += ((NI) 1);
					n = (NI)(n / i);
				} LA8: ;
			}
			i += ((NI) 1);
		}
	} LA1: ;
	{
		if (!!((n == ((NI) 1)))) goto LA12;
		HEX5BHEX5DHEX3D_159213(Result, n, ((NI) 1));
	}
	LA12: ;
}

static N_INLINE(NIM_BOOL, isfilled_118263)(NI hcode) {
	NIM_BOOL result;
	result = 0;
	result = !((hcode == ((NI) 0)));
	return result;
}

static N_INLINE(Slice88082, HEX2EHEX2E_102424)(NI a, NI b) {
	Slice88082 result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

N_NIMCALL(void, main_159650)(void) {
	NI N;
	TY159653 LOC1;
	Orderedtable159110 pf;
	N = nextint_159016(((NI) 0));
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = nimIntToStr(N);
	LOC1[1] = copyString(((NimStringDesc*) &TMP40));
	write_15505(stdout, LOC1, 2);
	memset((void*)(&pf), 0, sizeof(pf));
	memset((void*)(&pf), 0, sizeof(pf));
	primefactor_159102(N, (&pf));
	{
		NI k_159669;
		NI v_159670;
		NI h_159719;
		k_159669 = 0;
		v_159670 = 0;
		h_159719 = pf.first;
		{
			while (1) {
				NI nxt_159721;
				if (!(((NI) 0) <= h_159719)) goto LA4;
				nxt_159721 = pf.data->data[h_159719].Field1;
				{
					NIM_BOOL LOC7;
					LOC7 = 0;
					LOC7 = isfilled_118263(pf.data->data[h_159719].Field0);
					if (!LOC7) goto LA8;
					k_159669 = pf.data->data[h_159719].Field2;
					v_159670 = pf.data->data[h_159719].Field3;
					{
						NI i_159696;
						Slice88082 HEX3Atmp_159703;
						i_159696 = 0;
						memset((void*)(&HEX3Atmp_159703), 0, sizeof(HEX3Atmp_159703));
						HEX3Atmp_159703 = HEX2EHEX2E_102424(((NI) 0), (v_159670 - 1));
						{
							NI x_159707;
							NI HEX3Atmp_159709;
							NI HEX3Atmp_159711;
							NI res_159713;
							x_159707 = 0;
							HEX3Atmp_159709 = 0;
							HEX3Atmp_159711 = 0;
							HEX3Atmp_159709 = HEX3Atmp_159703.a;
							HEX3Atmp_159711 = HEX3Atmp_159703.b;
							res_159713 = HEX3Atmp_159709;
							{
								while (1) {
									TY159653 LOC14;
									if (!(res_159713 <= HEX3Atmp_159711)) goto LA13;
									x_159707 = res_159713;
									i_159696 = x_159707;
									memset((void*)LOC14, 0, sizeof(LOC14));
									LOC14[0] = copyString(((NimStringDesc*) &TMP48));
									LOC14[1] = nimIntToStr(k_159669);
									write_15505(stdout, LOC14, 2);
									res_159713 += ((NI) 1);
								} LA13: ;
							}
						}
					}
				}
				LA8: ;
				h_159719 = nxt_159721;
			} LA4: ;
		}
	}
	printf("%s\012", ((NimStringDesc*) &TMP49)? (((NimStringDesc*) &TMP49))->data:"nil");
	fflush(stdout);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_algorithmDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_timesDatInit000();
	stdlib_mathDatInit000();
	stdlib_tablesDatInit000();
	stdlib_macrosDatInit000();
	stdlib_posixDatInit000();
	stdlib_osDatInit000();
	stdlib_setsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_futureDatInit000();
	aoj_ntl_1_a_testDatInit000();
	stdlib_algorithmInit000();
	stdlib_sequtilsInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_timesInit000();
	stdlib_mathInit000();
	stdlib_tablesInit000();
	stdlib_macrosInit000();
	stdlib_posixInit000();
	stdlib_osInit000();
	stdlib_setsInit000();
	stdlib_streamsInit000();
	stdlib_futureInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	aoj_ntl_1_a_testInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, aoj_ntl_1_a_testInit000)(void) {
	main_159650();
}

NIM_EXTERNC N_NOINLINE(void, aoj_ntl_1_a_testDatInit000)(void) {
}

